### ISSUE TITLE
[DM:North] Gordok Tribute Chest - missing loot

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#10]
The Gordok Tribute chest should have a low chance (1-2%?) to drop the epic axe Treant's Bane. It is currently missing on the loot table. (Not sure how it interacts with Tribute event itself)

https://classic.wowhead.com/item=18538/treants-bane#contained-in-object

**Comment by VortexPrecision** [comment]
follow up:
https://github.com/VortexPrecision/PrecisionWoW/issues/14
