### ISSUE TITLE
[NPC] Cloud Skydancer react status

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#118]
Cloud Skydancer is the alliance flightmaster in Cenarion Hold, Silithus.
Currently, he is not part of any faction and Horde players can interact with him.

He should be part of Darnassus faction and hostile towards Horde players.

https://wotlk.evowow.com/?npc=15177

**Comment by VortexPrecision** [comment]
cannot reproduce he is hostile to me
![imagem](https://user-images.githubusercontent.com/71529592/100468600-a3881c00-30cc-11eb-9cea-d80e81f65ccb.png)
be careful if you're using rep commands on PTR because they can make you be friendly to hostile factions.
