### ISSUE TITLE
[Progression] First Aid profession

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#131]
First Aid profession had more different way of leveling until WotLK expansion, currently you can learn all First Aid from 1-300 from any First Aid trainer. In Vanilla, you only can learn maxskill 150 from trainer, then need to buy books from vendors out in the world until 225, then you need to do a quest to learn rest in Hammerfall/Theramore.
_____
### Removing WotLK spells
Following spells need to be removed from trainers until WotLK
(7924,10846,7929,10840,10841,18629,18630,19903,54254,7925,10847,19902)
Expert First Aid
Artisan First Aid
Heavy Silk Bandage
Mageweave Bandage
Heavy Mageweave Bandage
Runecloth Bandage
Heavy Runecloth Bandage

Also consider removing First Aid from Death Knights until WotLK, as they start with it already fully skilled and can skip quest.

First Aid trainer npcs (trainers in northrend not included)
2326,2327,2329,2798,31813373,4211,4591,5150,5759,5939,5943,6094,16272,16662,16731,17214,17424,18990,18991,19184,19478,22477,33621
_____
### Restoring old quest rewards
Quests 6622 and 6624 (quests needed to learn First Aid skill up to 300) currently reward 20 Heavy Runecloth Bandages and a gray vendor item (item id 49192 for Horde version, 49193 for Alliance).

These quests actually should reward 20 Heavy Runecloth Bandages and the spell 10847 should be cast on the player. Gray items need to be removed as these were rp/flavour items that were replacement as quest reward in WotLK.
_____
### Restoring old method of learning high level bandages
npcs 12920 and 12939 currently have no option of learning Heavy Mageweave Bandage, Runecloth Bandage and Heavy Runecloth Bandage.

If current First Aid skill is minimum 240 and player does not know Heavy Mageweave Bandage, player should be able to click gossip option that casts spell 10843 on player, which says:
_Teach me how to create and apply a Heavy Mageweave Bandage, Doctor._

If current First Aid skill is minimum 260 and player does not know Runecloth Bandage, player should be able to click gossip option that casts spell 18631 on player, which says:
_Teach me how to create and apply a Runecloth Bandage, Doctor._

If current First Aid skill is minimum 290 and player does not know Heavy Runecloth Bandage, player should be able to click gossip option that casts spell 18632 on player, which says:
_Teach me how to create and apply a Heavy Runecloth Bandage, Doctor._
_____
https://youtu.be/4YO4jbhtGk8?t=504

**Comment by VortexPrecision** [comment]
12920,12939

**Comment by VortexPrecision** [comment]
Triage quests need to be rewritten.
