### ISSUE TITLE
Lock and Load Talent - Survival Hunter

### ISSUE THREAD

**Issue by Monziltinks** [VortexPrecision/PrecisionWoW#136]
[The Lock and Load talent](https://wotlk.evowow.com/?spell=56344) has a chance to proc on every ability a hunter uses instead of only proccing from Explosive Trap, Immolation Trap and Black Arrow.
This includes auto shot, which means you are almost guaranteed to proc it on CD.

**Comment by 11011010** [comment]
Maybe a good idea to keep it buffed :-D

**Comment by VortexPrecision** [comment]
https://github.com/TrinityCore/TrinityCore/commit/746b838870e93d9843a089613ce7f1cd160b6ea5

**Comment by VortexPrecision** [comment]
proc should be on periodic ticks and not by hitting the target (for black arrow and such)
