### ISSUE TITLE
LBRS - "Seal of Ascension" quest

### ISSUE THREAD

**Issue by Orenoken** [VortexPrecision/PrecisionWoW#139]
The item "Gemstone of Spirestone" does not seems to be dropping off Highlord Omokk in Lower Blackrock Spire. It is the sixth time I reset the dungeon but the item won't drop.

All other gemstones + unadorned Seal of Ascension drop off their respecting npcs correctly.

**Comment by awatenn** [comment]
Drop rate was changed to 30% on all affected bosses with #21 - just need to be lucky! I got it after my 8th kill. Other bosses don't drop it 100% either.
https://imgur.com/Y4YcozB

**Comment by VortexPrecision** [comment]
> 
> 
> Drop rate was changed to 30% on all affected bosses with #21 - just need to be lucky! I got it after my 8th kill. Other bosses don't drop it 100% either.
> https://imgur.com/Y4YcozB

As reported here, it drops, the drop rate is vanilla.
