### ISSUE TITLE
[Spells/Hunter] Eagle Eye

### ISSUE THREAD

**Issue by Talthos** [VortexPrecision/PrecisionWoW#146]
**Wowhead/WotLK database link(s):**
[Eagle Eye (Wowhead, current retail)](https://www.wowhead.com/spell=6197/eagle-eye)

[Eagle Eye (Rising-Gods, a WotLK-era database site)](https://db.rising-gods.de/?spell=6197)

**Description:**
(Testing was performed on the PTR Vanilla realm)

When using a macro to chain-cast Eagle Eye (which can allow you to see the opposite end of a continent, if you keep at it long enough), NPCs do not render after the first cast.

**How it should work:**

 Any NPCs around the current position of Eagle Eye should render, up to the normal render distance.

**How to replicate issue:**

Use the following macro to chain-cast Eagle Eye (and yes, the exclamation point is correct):

/cast !Eagle Eye

Notice how NPCs do not render at any Eagle Eye location beyond the first cast.

**Any other documentation that could be helpful:**
[A retail video from 2007 that showcases this exact functionality of Eagle Eye, prior to a change that required the exclamation mark to be added to the macro (which one of the comments helpfully points out)](https://www.youtube.com/watch?v=db3sYKRf_AQ)

[A 2007 Wowhead forum topic that directly refers to the above-mentioned macro](https://www.wowhead.com/forums&topic=6925)

[A 2008 Wowhead forum topic, also mentions the macro directly](https://www.wowhead.com/forums&topic=120822)

[A 2009 Wowhead forum topic, which also mentions the macro and its function directly](https://www.wowhead.com/forums&topic=159755)

[Another 2009 Wowhead forum topic, also mentions the macro](https://www.wowhead.com/forums&topic=102770)

[A 2009 MMO Champion forum topic, also mentions the macro](https://www.mmo-champion.com/threads/674431-Eagle-Eye-Macro)

**Comment by Broker-Precision** [comment]
obsolete
