### ISSUE TITLE
[Item/Trinket] Mark of the Champion not providing buff

### ISSUE THREAD

**Issue by Talthos** [VortexPrecision/PrecisionWoW#147]
**Wowhead/WotLK database link(s):**

The item itself:
[Mark of the Champion (Wowhead, current retail)](https://www.wowhead.com/item=23206/mark-of-the-champion)

[Mark of the Champion (Wowhead Classic database)](https://classic.wowhead.com/item=23206/mark-of-the-champion)

[Mark of the Champion (Rising-Gods, a WotLK-era database site)](https://db.rising-gods.de/?item=23206)

And the passive buff it's supposed to provide:
[Champion of the Dawn (Wowhead, current retail)](https://www.wowhead.com/spell=29112/champion-of-the-dawn)

[Champion of the Dawn (Wowhead Classic database)](https://classic.wowhead.com/spell=29112/champion-of-the-dawn)

[Champion of the Dawn (Rising-Gods, a WotLK-era database site)](https://db.rising-gods.de/?spell=29112)

**Description:**

(Testing was performed on the PTR Vanilla realm. I tested the attack power version of the trinket; might be a good idea to check the spellpower version of the trinket)

Equipping the Mark of the Dawn trinket does not provide the passive buff that is described in its tooltip (more attack power versus undead and demons, and allows the various scourgestones to drop from mobs in the Plaguelands).

**How it should work:**

Equipping the Mark of the Dawn trinket should provide the passive buff that is described in its tooltip.

**How to replicate issue:**

Equip the Mark of the Dawn trinket, and notice that the passive buff isn't provided.

**Comment by VortexPrecision** [comment]
fixed on changelog:
https://discord.com/channels/756613279211585576/756615548774645830/816908943040839680

![image](https://user-images.githubusercontent.com/71529592/136182630-ed550687-6240-4967-829a-fa1e627123aa.png)
