### ISSUE TITLE
[Quests] The Fall of Kel'Thuzad

### ISSUE THREAD

**Issue by Talthos** [VortexPrecision/PrecisionWoW#148]
**Wowhead/WotLK database link(s):**

The item itself:
[The Phylactery of Kel'Thuzad (Wowhead, current retail)](https://www.wowhead.com/item=22520/the-phylactery-of-kelthuzad)

[The Phylactery of Kel'Thuzad (Wowhead Classic database)](https://classic.wowhead.com/item=22520/the-phylactery-of-kelthuzad)

[The Phylactery of Kel'Thuzad (Rising-Gods, a WotLK-era database site)](https://db.rising-gods.de/?item=22520)

The quest:
[The Fall of Kel'Thuzad (Wowhead, current retail)](https://www.wowhead.com/quest=9120/the-fall-of-kelthuzad)

[The Fall of Kel'Thuzad (Wowhead Classic database)](https://classic.wowhead.com/quest=9120/the-fall-of-kelthuzad)

[The Fall of Kel'Thuzad (Rising-Gods, a WotLK-era database site)](https://db.rising-gods.de/?quest=9120)

And the NPC that you'd normally hand this quest to:
[Father Inigo Montoy (Wowhead, current retail)](https://www.wowhead.com/npc=16113/father-inigo-montoy)

[Father Inigo Montoy (Wowhead Classic database)](https://classic.wowhead.com/npc=16113/father-inigo-montoy)

[Father Inigo Montoy (Rising-Gods, a WotLK-era database site)](https://classic.wowhead.com/npc=16113/father-inigo-montoy)

**Description:**

(Testing was performed on the PTR Vanilla realm.)

This quest currently has you turning it in with Commander Eligor Dawnbringer, rather than Father Inigo Montoy.

**How it should work:**

Father Inigo Montoy should be the NPC that you return this quest to.

**How to replicate issue:**

Obtain the quest from The Phylactery of Kel'Thuzad, and note that the incorrect turn-in NPC is being used (Commander Eligor Dawnbringer), rather than the correct one (Father Inigo Montoy).

**Comment by Broker-Precision** [comment]
Fixed
