### ISSUE TITLE
[Items] Cluster Launcher

### ISSUE THREAD

**Issue by Talthos** [VortexPrecision/PrecisionWoW#149]
**Wowhead/WotLK database link(s):**

[Cluster Launcher (Wowhead, current retail)](https://www.wowhead.com/item=21570/cluster-launcher)

[Cluster Launcher (Wowhead Classic database)](https://classic.wowhead.com/item=21570/cluster-launcher)

[Cluster Launcher (Rising-Gods, a WotLK-era database site](https://db.rising-gods.de/?item=21570)

**Description:**
(Testing was performed on the PTR Vanilla realm.)

[Placing a Cluster Launcher currently places a standard Firework Launcher model in the world.](https://wow.zamimg.com/uploads/screenshots/normal/83858-firework-launcher.jpg)

It still functions as a Cluster Launcher, but the model is incorrect.

It's also (incorrectly) using the firing noises for the standard Firework Launcher.

**How it should work:**

[Placing a Cluster Launcher should place _this_ model in the world.](https://wow.zamimg.com/uploads/screenshots/normal/273014-cluster-launcher.jpg)

Additionally, the Cluster Launcher should use "G_FireworkLauncher02Custom0.wav" as its 'firing' sound.

[Here's a video that demonstrates both the correct sound and the correct model (the player starts launching cluster rockets around the 53 second mark).](https://www.youtube.com/watch?v=YoqWeSfFi2g)

**How to replicate issue:**

Place a Cluster Launcher, and note the incorrect model and incorrect firing noises.

**Comment by Broker-Precision** [comment]
fixed
