### ISSUE TITLE
Warrior - Charge - problems

### ISSUE THREAD

**Issue by serkantarcan** [VortexPrecision/PrecisionWoW#151]
Charge:

- [x]  only makes the character go in a straight line towards the target,
- [x]  stops auto-attack after lands,
- [x] doesn't stun the target,
- [x] sometimes makes you fall into oblivion and you die.

**Comment by VortexPrecision** [comment]
![image](https://user-images.githubusercontent.com/71529592/102513256-e5303500-4082-11eb-9552-73ea24f7164d.png)

stuns for me and doesn't stop auto-attacks.

**Comment by Broker-Precision** [comment]
Confirmed below are working as intented:
 stops auto-attack after lands,
 doesn't stun the target,
