### ISSUE TITLE
Quest - Massacre At Light's Point

### ISSUE THREAD

**Issue by treskoo** [VortexPrecision/PrecisionWoW#153]
NPC's are attacking the minecart under transport. This should not be happening.

**How it's right now**
https://drive.google.com/drive/folders/160RNCDQ6toIGiRpbejzUzYZuBXVMH_is

**How it should be**
https://www.youtube.com/watch?v=h4aHk7H6XfA&start=20s

**Comment by Nastybitch** [comment]
I've removed footage for it, as it get fixed, issue deserves it's closing.
