### ISSUE TITLE
Vanilla - Death Knight? - TBC races? - NO!!!

### ISSUE THREAD

**Issue by serkantarcan** [VortexPrecision/PrecisionWoW#154]
You had a brilliant idea and done a great job. Don’t screw it with DK’s and TBC races in VANILLA!
Ok?
That’s hands down a terrible terrible mistake.

**Comment by VortexPrecision** [comment]
Hello, i can accept this as a suggestion but not as a issue. Thank you anyway.

**Comment by serkantarcan** [comment]
Hello again 😄

Thanks for quick reply. Forgive me if I were so direct but I am expecting a
lot from people who came up with such a great idea and did a marvelous job.
Yes, take this as a suggestion but a very serious one please.
Keep up the good work!
Cheers.
