### ISSUE TITLE
[Quest / Event] Balance Of Light & Shadow

### ISSUE THREAD

**Issue by pzyk0tik** [VortexPrecision/PrecisionWoW#156]
Lots of bugs with this scripted event. I know, because I did it in vanilla and in Blizzard's recent version of Vanilla.

1. If you die during the event Aris and the peasants will stop being visible. If you unequip and requip the trinket they will suddenly work again.

2. The event never ends. I died, took resurrection sickness and literally it kept rolling

3. The peasants don't seem to die from their diseases or at least I've yet to see it happen and I've tried the event 3 times

**Comment by VortexPrecision** [comment]
Thank you for the report, i can confirm that the peasents die from the diseases indeed. The rest is fixed :)
