### ISSUE TITLE
[Spells / Talents] Clearcasting disappears too early for channeled spells

### ISSUE THREAD

**Issue by burnscar** [VortexPrecision/PrecisionWoW#157]
From tooltip: "The Clearcasting state reduces the mana cost of your next damage spell by 100%."

Current behaviour is that Clearcasting, if active, gets consumed the moment you finish casting a damaging spell and reduces the mana cost of that to 0. This applies to all mage damage spells.

The problem with this behaviour is that channeled spells (Blizzard and Arcane Missiles) consume mana when you _start_ casting them, and trigger the Clearcasting effect _during_ the cast. This means that if you receive a Clearcasting buff, it's always halfway through casting of a spell that has already consumed mana, and the buff will fall off the moment you finish casting, doing nothing. Next spell costs full amount of mana because Clearcasting buff is already gone.

What should happen: Clearcasting should make your next spell free, regardless of whether the proc was triggered by channeling, spamming Frostbolts or whatever else.

Perfectly blizzlike behaviour is actually idiotic and I'm not going to describe it (it's probably hard to code, too), but what we could get is some simple exception - IF the spell that triggers Clearcasting is channeled (you could just name them, there's only two atm - AM and Blizzard), THEN Clearcasting doesn't disappear when you finish a cast, but instead stays up for one more spell.

**Comment by Nastybitch** [comment]
https://drive.google.com/file/d/1Bveg-cxf6rAyuZy3qrYTmsaO0ze3o7D-/view?usp=sharing
pay attention for proc bar and mana which get wasted
and iirc it's somewhat "old" and known bug for precision

**Comment by VortexPrecision** [comment]
fixed recently
