### ISSUE TITLE
[Spells / Talents] Righteous Vengeance and alikes

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#158]
Currently we got no stacking on DoTs from those: [Unholy Blight](https://wotlkdb.com/?spell=49194) for DK, [Righteous Vengeance](https://wotlkdb.com/?spell=53382) for Paladin, [Deep Wounds](https://wotlkdb.com/?spell=12867) for Warrior (Partially), [Piercing Shots](https://wotlkdb.com/?spell=53238) for Hunters and [Ignite](https://wotlkdb.com/?spell=12848) for Mages (Partially). Surprisingly, HoT from [Sheath of Light](https://wotlkdb.com/?spell=53503) (Paladin) is working correct.
Logic behind all those talents:
When you meet conditions DoT is placed, and if you met conditions before old DoT runs out remaining damage should be added to new DoT, not just refresh with new value.
For example, let us get fire mage with 10k crits and Ignite talent, which we put into 40% damage over 10 seconds with ticks every second (for simplicity), it's 400 damage per tick for 4k damage overall, let us say he scores another 10k crit after 2 ticks of original DoT meaning 3.2k of residual value, it should be added for new 4k for total 7.2k over 10 seconds DoT with 720 damage ticks... and so on, and so on...
At this moment most of these talents do not include old procs at all, those which are labeled Partially got somewhat of limitation in number of procs could be summarized meaning they grow in value to some degree, but when limit met start to, sometimes, lose value.

Easiest way to reproduce is to .add 5555111 and test them with over 100% crit chance.

**Comment by Nastybitch** [comment]
P.S. I only tested talents I'm interested in, there may be more with same mechanic

**Comment by Marluxius** [comment]
Only Piercing Shot didn't seem to work as intended when I tested.
Didn't check for DK's Unholy Blight since they'll be disabled.
