### ISSUE TITLE
[Quests / Spells / Class] Death Knight feedback

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#159]
Minor, negliglible bug that ruins that retail like scripting which kept till you got [If Chaos Drives, Let Suffering Hold The Reins](https://wotlkdb.com/?quest=12678) quest, There should be Citizens of Havenshire who got shot by skeleton archers above with almost no HP left.
[The Light of Dawn](https://wotlkdb.com/?quest=12801) - there is no 5 minute delay, and if Darion runs away from you or you from him, then the event is going to be [reset](https://drive.google.com/file/d/1Y85DsMKF9yUpyAb-imo2jTgJx_ibIN26/view?usp=sharing).
Also there's some server specific difficulties: combination of very fast mob respawn, gear locking, damage/healing nerf and the fact that mobs sometimes aggro through textures allow them to just obliterate you sometimes...

**Comment by Nastybitch** [comment]
Also there were some more insignificant or TC common bugs, like city guards ignore you, not pointing fingers and calling names nor throwing stuff in you or even spitting, which also ruins retail scripting and RP part for some degree.

**Comment by Progressive335** [comment]
_And final and most vital bug so far is limitation DKs to 60% mounts only:
When you finish Into the Realm of Shadows you'll get 60% mount and 75 riding (and it's fair with 150 riding gated to 60 and cost 1k golds), but it prevents you from ever getting 150 skill and 100% mount at this moment._
this is not a bug, this is intended.

**Comment by VortexPrecision** [comment]
_And final and most vital bug so far is limitation DKs to 60% mounts only:
When you finish Into the Realm of Shadows you'll get 60% mount and 75 riding (and it's fair with 150 riding gated to 60 and cost 1k golds), but it prevents you from ever getting 150 skill and 100% mount at this moment:__

not a bug. intended.

**Comment by Nastybitch** [comment]
"DKS wont receive 100% riding. they will get the 60% version instead."

"it's fair with 150 riding gated to 60 and cost 1k golds" -  is where I agreed that's fair, but, for instance, paladins got their mounts for free (at least on PTR), also real problem is "it prevents you from ever getting 150 skill and 100% mount at this moment" which is quite class-based discrimination! What's even more ruins DKs Quality of Life...

**Comment by Nastybitch** [comment]
A guide to my feedback:
"First of all a minor, negliglible bug" - first bug
"Next is" - second bug
"Final non-blizzlike quest" - third bug
"Also there's some server specific difficulties" - not a bug, but things requires some fine-tuning
"And final and most vital bug so far" - fourth bug
Thanks for your attention!

**Comment by Nastybitch** [comment]
![image](https://user-images.githubusercontent.com/57399792/102192297-a5731d00-3ecb-11eb-9ec3-31dee64c68b0.png)
that's what DK get when trying to use 100% mount

**Comment by VortexPrecision** [comment]
> ![image](https://user-images.githubusercontent.com/57399792/102192297-a5731d00-3ecb-11eb-9ec3-31dee64c68b0.png)
> that's what DK get when trying to use 100% mount

That's because you don't have riding and you have learned a mount from the account wide system.

**Comment by VortexPrecision** [comment]
> "DKS wont receive 100% riding. they will get the 60% version instead."
> 
> "it's fair with 150 riding gated to 60 and cost 1k golds" - is where I agreed that's fair, but, for instance, paladins got their mounts for free (at least on PTR), also real problem is "it prevents you from ever getting 150 skill and 100% mount at this moment" which is quite class-based discrimination! What's even more ruins DKs Quality of Life...
> 
> And about #153 it was kind of my previous report as were based on my feedback and used my original shooting (I just used to get issues with github login and asked other people to post it here, also, before posting that big report I asked that person to close or delete his issue) there's no other issues mentions things described here opened or closed...
> 
> Also I feel that all of that belongs to a single report as it's all connected to DKs starter chain and represents server to DK playerbase who, most likely, knows how it should work/feel and can get a wrong idea of realm in general once they notice how it's broken here and work flawlessly on TC master...
> 
> Oh, and DKs do get their free first aid at this moment. And feel free to close this issue and make smaller ones if it fits you more, I'm too going to respect your vision in future, but this specific report is fine from my point of view (only issue with it is TMI, but, to be honest we got Too Much Bugs with DK first steps now, so....)

About pala and warlock mounts that only happens on PTR. The only thing I suggested is to put all this in sepparate reports. I don't see too much bugs, I see some minor/cosmetic/rp stuff that needs fixing indeed but it's not a prio and doesn't affect DK class itself.

**Comment by Nastybitch** [comment]
"That's because you don't have riding and you have learned a mount from the account wide system."
I know, problem is that there's no way to get riding on current Vanilla PTR...

**Comment by VortexPrecision** [comment]
> "That's because you don't have riding and you have learned a mount from the account wide system."
> I know, problem is that there's no way to get riding on current Vanilla PTR...
> 
> Just tell me that limiting DKs to 60% mount for at least whole Vanilla duration is intended or it's obvious bug and should be fixed ASAP. :3
> 
> "doesn't affect DK class itself"
> Inaccessible 100% mount affecting DKs for sure, and mining cart bug can be confusing for many players.

Afaik you get 10k gold so you can buy riding in a horde city. It's not a bug, it's an intended change, DKS can get riding normally as other classes, they just wont obtain it freely.

**Comment by Nastybitch** [comment]
[For instance](https://drive.google.com/file/d/1mjPp7PkEXwMuJPg96d82MYPxEWjgXzCM/view), once you get 75 riding 150 got locked, no matter how you got 75 that's bug I try to report.

**Comment by Nastybitch** [comment]
![image](https://user-images.githubusercontent.com/57399792/102351938-463f0680-3fb8-11eb-91d3-a97b16a66fc3.png)
cart is fixed
![image](https://user-images.githubusercontent.com/57399792/102351995-5c4cc700-3fb8-11eb-9c9e-77fa1862601d.png)
riding as well
