### ISSUE TITLE
T3 mage

### ISSUE THREAD

**Issue by 11011010** [VortexPrecision/PrecisionWoW#160]
T3 6 piece bonus does not get consumed after a spell, It stays.

It should get consumed ( like with hemorrhage from rogue I think)

**Comment by burnscar** [comment]
The tooltip clearly implies that it should stay and buff "subsequent spells", however the actual blizzlike behaviour back in retail vanilla was that it got consumed by a single hit from any spell (including DoTs), making it pretty damn useless.
I like the current implementation as it's truthful to what the game explicitly tells you about the effect's behaviour, but... it is a little overpowered. A compromise (making it eat charges like Hemo) would be a decent option.
