### ISSUE TITLE
[Creatures] Citizen of New Avalon

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#162]
In [enraged](https://wotlkdb.com/?spell=52262) state [they](https://wotlkdb.com/?search=Citizen+of+New+Avalon) deal impressive damage, with all nerfs DKs received unlucky pull could lead to no good.

**Comment by Nastybitch** [comment]
More of a suggestion than report.

**Comment by Broker-Precision** [comment]
No issue, Also confirmed damage not to be over the top.
