### ISSUE TITLE
[Zone] New Avalon Town Hall

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#163]
There's some weird pathing, especially at entrance.

**Comment by Nastybitch** [comment]
Low priority, can attach footage if required.

**Comment by VortexPrecision** [comment]
footage please.

**Comment by Nastybitch** [comment]
[Check those Scarlet Crusaders pathing, one even got stuck and evades.](https://drive.google.com/file/d/1wURBeoXDDDsf9zptnhwFn5BGGxSIRMix/view?usp=sharing)
