### ISSUE TITLE
[Zone] DK starter area

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#165]
There's a list of issues there, mostly caused by reduced respawn timer on mobs, my suggestion is to rollback them to regular timers with little exceptions for QoL of fresh DKs:
[Citizen of Havenshire](https://wotlkdb.com/?search=Citizen+of+Havenshire) - as there no additional trampled version spawns + they're only mobs gating questing speed to this point
[Scarlet Miner](https://wotlkdb.com/?search=Scarlet+Miner) - if we gonna get many DKs start on same time they could turn one more gate
[Scarlet Fleet Defender](https://wotlkdb.com/?search=Scarlet+Fleet+Defender) - even atm they respawn very slowly, you'll need to get onto other ship in order to get credit
[Mayor Quimby](https://wotlkdb.com/?npc=28945) - as he's unique NPC and every DK  needs his head
[New Avalon Registry](https://wotlkdb.com/?object=190947) - as unique game object every DK need
[New Avalon Patrol Schedule](https://wotlkdb.com/?object=191084) - same as registry
[Ellen Stanbridge](https://wotlkdb.com/?quest=12738) &co - those argent NPC can turn one more gate, full list within [Opens Quests] tab
Also need to confirm [Koltira](https://wotlkdb.com/?npc=28912) respawn timer for [Bloody Breakout](https://wotlkdb.com/?quest=12727), because if it's high enough it can cause time loss too.

**Comment by VortexPrecision** [comment]
if a DK tries to duel a NPC while in a mount, it bugs and give them a lot of speed.

**Comment by Broker-Precision** [comment]
Respawn timers adjusted.
