### ISSUE TITLE
[Gear] Pala T1 8/8 100% proc chance

### ISSUE THREAD

**Issue by dweepdwoop** [VortexPrecision/PrecisionWoW#166]
Pala 8/8 T1 set bonus has a 100% proc chance
Should be 1ppm/3% according to classic proc rate tests like https://us.forums.blizzard.com/en/wow/t/lawbringer-8-set-bonus-proc-rate/343326

**Comment by Nastybitch** [comment]
https://classic.wowhead.com/spell=21747/lawbringer#comments
As additional evidence.
