### ISSUE TITLE
Fear [All type]

### ISSUE THREAD

**Issue by 11011010** [VortexPrecision/PrecisionWoW#168]
There seems to be a visual difference about the location where the feared person is.

Ways to replicate: including a skillful drawing from my child.
Get 3 Players ( 1, 2, 3)

1. Player 1 Fears player 3 ( player 3 needs to be moving/running )
2. Player 3 runs away in fear to location b 
3. Player 1 and 2 see player 3 at location a.
4. Player 3 teleports to right location after the fear ends.

Replication chance ~5 % or lower
Here the awesome drawing.
![image](https://user-images.githubusercontent.com/69040574/102513006-bb373c80-409b-11eb-8cab-e68aa68c855a.png)

Thanks to Elfosious for reporting and helping me draw ;)

**Comment by 11011010** [comment]
![thats how it looks like](https://user-images.githubusercontent.com/69040574/102515786-39491280-409f-11eb-942d-c8b32dabbee1.gif)
professional video from Elfosious

**Comment by VortexPrecision** [comment]
i did a fix, should be tested again

**Comment by VortexPrecision** [comment]
Fixed recently
