### ISSUE TITLE
Devilsaur, Tyrant Devilsaur and Ironhide Devilsaur respawn timers.

### ISSUE THREAD

**Issue by supmonkas** [VortexPrecision/PrecisionWoW#169]
All databases I've checked say the respawn timers are suppose to be 10 minutes, I've tested and confirmed that they are currently 15 minutes on the PTR, with 1 of the 4 spawns being 11-12 minutes respawn.

**Comment by VortexPrecision** [comment]
You tested it wrong, they are all 10 minutes respawn.
