### ISSUE TITLE
Aggro range overtuned

### ISSUE THREAD

**Issue by AdmiralAwsum** [VortexPrecision/PrecisionWoW#178]
Mobs seem to aggro too quickly with the aggro range being way too high.

**Comment by Sylveighty** [comment]
even gray level mobs aggro like they're not gray level

**Comment by mofino22** [comment]
also the aggroed mobs leash too many adjacent ones with them making it difficult for some mob packs to survive

**Comment by TheRealestMcCoy** [comment]
The aggro radius of a mob having the same level as the player is roughly 20 yards (~ 18 meters)
Aggro radius varies with level difference at a rate of roughly 1 yard/level.
Minimum aggro radius for a mob seems to be combat range (5 yards).
A Hunter's pet seems to ignore the minimum aggro radius for low level mobs, even when controlled through  [Eyes of the Beast].
Aggro radius is capped at a maximum of 45 yards, that is, when the mob is 25 or more levels higher than the player.
Vertical distance seems to be weighted much more heavily than horizontal distance. A mob standing on a ledge 4 yards above your head can fail to aggro even if standing 4 yards away from the same mob on level ground will draw aggro.https://vanilla-
wow.fandom.com/wiki/Aggro_radius#:~:text=Aggro%20radius%20is%20capped%20at,levels%20higher%20than%20the%20player.

**Comment by VortexPrecision** [comment]
seems fixed. reopen if it maintains.
