### ISSUE TITLE
Mage Blizzard breaks after 1-2 Ticks

### ISSUE THREAD

**Issue by AdmiralAwsum** [VortexPrecision/PrecisionWoW#179]

**Comment by burnscar** [comment]
Also true for Arcane Missiles and Mind Flay, reportedly.
There seems to be a new issue with channeled spells that wasn't present on PTR.

**Comment by mengh3** [comment]
Noticed this was happening whenever I get a judge of light proc.

**Comment by VortexPrecision** [comment]
> Noticed this was happening whenever I get a judge of light proc.

that's useful info, thanks.

**Comment by VortexPrecision** [comment]
fixed
