### ISSUE TITLE
Rune of Duty requires wrong reputation for alliance

### ISSUE THREAD

**Issue by PrecisionWisy** [VortexPrecision/PrecisionWoW#182]
The level 40 version of Rune of Duty (WSG trinket) requires Warsong Outriders reputation instead of Silverwing Sentinels
Item: https://wotlkdb.com/?item=21567#sold-by-npc
What the vendor sells: https://imgur.com/a/ozqbqDu

**Comment by VortexPrecision** [comment]
![image](https://user-images.githubusercontent.com/71529592/104507309-704b0f00-55de-11eb-8dff-1f145e121e00.png)
"...and your client may already cached the opposite faction requirement."

just clear your cache.
