### ISSUE TITLE
Melee & Spell leeway - Super important for PVP and gameplay feel

### ISSUE THREAD

**Issue by dweepdwoop** [VortexPrecision/PrecisionWoW#186]
I'll point out that I copied this over from a well-explained github report from a TBC server since the exact mechanic should be present in WotlK, without it melee have to stand directly on top of people to hit them and with server-side movement updates being few and far inbetween it can be extremely frustrating especially when the enemy you're fighting is lagging, and for casters it means casts being cancelled as soon as enemies run out of the spell's range instead of tethering for a few yards longer as has always been present in WoW (and still is), without further redo:

The Problem:
Currently there is no "moving range leeway" for ranged spells, melee spells & auto-attack.
Video I made: https://www.youtube.com/watch?v=5YzXpKaGCe8

How it should work:
When conditions are met, server should allow +2.66 yards to your ranged spells, melee spells & auto-attack.

Conditions:
You and your target must both be moving, you both also has to be moving with a "running animation", meaning both of you has to move > 0.7 of normal movement speed(this is where your character switch from walking to running animation).

Examples:
Use Curse of Exhaustion on target, target is now at 0.7 of normal movement speed, target starts walking.
Use Curse of Exhaustion on target which has a 8% increased movement speed boot enchant, target is now at 0.76 of normal movement speed, target will still be "running".

Proof:
How it's calculated in the 2.4.3 client: http://i.imgur.com/PxKWgdQ.png

Videos of this mechanic:
Retail: https://youtu.be/_DgUcqXwtwk?t=2m
Other server: https://www.youtube.com/watch?v=L8WhIo1l8Aw

How to reproduce: Mimic what is done in the videos.

**Comment by VortexPrecision** [comment]
fixed recently
