### ISSUE TITLE
Undercity mage quest not working properly

### ISSUE THREAD

**Issue by Fuokko** [VortexPrecision/PrecisionWoW#188]
There is a mage quest in undercity. You summon voidwalkers 1 by 1 with a scrool. Then you capture them in a box. Only 1 voidwalker coming and after you capture it no more you can summon. Using scrool doesnt work after first one

**Comment by VortexPrecision** [comment]
wrong/invalid/incomplete report.

you're referring to warlock class and voidwalker quest.
this quest works correctly.
