### ISSUE TITLE
Warrior Prot Talent One-Handed Weapon Specialization

### ISSUE THREAD

**Issue by Junodruid** [VortexPrecision/PrecisionWoW#19]
When you have 5/5 talents it will not add  x10% damage when you wield a one-hander. Defensive stance will still have -5% negative damage when it should be +5% (105)

"Once you hit 40, you need to be using a One-hander and Shield. At 40 you get Shield Slam and by then you can have 5/5 in One-handed Weapon Specialization which will eliminate (and then some) the penalty of being in Defensive Stance. This is the build I'd aim for at 40."

Source: https://www.wowhead.com/forums&topic=96421

**Comment by Junodruid** [comment]
Paladin and Druid works with their respective talents which increases with weapon/bear form.

**Comment by VortexPrecision** [comment]
not a bug. works fine.
