### ISSUE TITLE
Hunter pet pathing

### ISSUE THREAD

**Issue by Mugera500** [VortexPrecision/PrecisionWoW#190]
Hunter pets either standing out of range of a mob and just stares at it, or it does a dance with the mob, continously running around it trying to get in range while the mob does the same...

really annoying in tight mob density areas due to the constant moving

**Comment by VortexPrecision** [comment]
can you give me a example of mob and a example of pet for both situations? thanks.

**Comment by VortexPrecision** [comment]
this was fixed in a previous update.
