### ISSUE TITLE
[Spells] Unholy DK double dipping

### ISSUE THREAD

**Issue by Nastybitch** [VortexPrecision/PrecisionWoW#191]
There's some spells and effects which must be whitelisted from double dipping:
![image](https://user-images.githubusercontent.com/57399792/102739268-b9040500-435d-11eb-9cdc-7e703bd07740.png)
regular melee strike (as base for some talents), highest crit is 387
![image](https://user-images.githubusercontent.com/57399792/102739324-de910e80-435d-11eb-87ad-6ff4e836b5b5.png)
[Necrosis](https://wotlkdb.com/?spell=51465), 387*.2 = 77, but we got 53 highset
![image](https://user-images.githubusercontent.com/57399792/102739398-244dd700-435e-11eb-909c-9af42b614033.png)
[Blood-Caked Strike](https://wotlkdb.com/?spell=49628) 387*.625 = 242, not 124 (as, iirc, it should also take [Ebon Plaguebringer](https://wotlkdb.com/?spell=51161) as 3rd disease not only for DS heals, but for damage as well)
![image](https://user-images.githubusercontent.com/57399792/102739680-d5547180-435e-11eb-89eb-817a72b4e369.png)
[Scourge Strike](https://wotlkdb.com/?spell=55090) 726 highest crit
![image](https://user-images.githubusercontent.com/57399792/102739763-1187d200-435f-11eb-9815-e87a904692f1.png)
shadow part which should be 726*.36 = 261 (also should be noted that EBP bonus and a likes aren't taken into account, boosting it even further), but we got 182 only
![image](https://user-images.githubusercontent.com/57399792/102740184-46e0ef80-4360-11eb-80be-3e7f84756e41.png)
[Death Coil](https://wotlkdb.com/?spell=47541) 321 lowest hit
![image](https://user-images.githubusercontent.com/57399792/102740304-84457d00-4360-11eb-800b-6d07767c15c0.png)
[Unholy Blight](https://wotlkdb.com/?spell=49194) ticking every second for 10 seconds 10% of DC total, which means 1% per tick (stacks value) we got lowest tick for 2 damage, while it should be 321*.01=3

In case someone not sure with third disease (still, even with 2 diseases we got hit by dip twice):
[EJ guide from retail 3.3.5a](https://web.archive.org/web/20160515040154/http://forums.elitistjerks.com/forums/topic/71616-unholy-dps-335-king-of-anything/) stating: "Cool and all, but does that explain why the shadow portion of Scourge Strike deals more than the stated 36% of the physical portion?" which clearly shows 3(!) x12% and the answer with actual %age is somewhat we are not even near of "Yes, it does. Double-dipping is the culprit. After you factor in all of the previously mentioned buffs and talents, you'll find that the shadow portion will ultimately deal 53.2% for Blood builds (56.2% in Frost builds) of the physical portion (less partial resists)."

**Comment by VortexPrecision** [comment]
added missing exceptions.
