### ISSUE TITLE
The Defias Brotherhood

### ISSUE THREAD

**Issue by TheRealestMcCoy** [VortexPrecision/PrecisionWoW#198]
Quest ID: 155
NPC ID: 467

What's Wrong: The traitor does not attack or help fight any thing.

What should happen: The traitor should help fight the defias.

Video from classic. You can see the trairot starts to help this hunter but the hunter kills before he reaches his target.
https://youtu.be/_XVhZfSkBfM?t=174

**Comment by Broker-Precision** [comment]
Fixed
