### ISSUE TITLE
[Argent Dawn Reputation] Scholomance mobs not giving rep

### ISSUE THREAD

**Issue by blade7606** [VortexPrecision/PrecisionWoW#199]
Self Explanatory. Haven't tested strat yet

**Comment by VortexPrecision** [comment]
some of the rep is limited to a certain amount , for example there are some mobs that will grant you rep until some rank. thank is probably the case.

**Comment by VortexPrecision** [comment]
check this for more info
https://github.com/VortexPrecision/PrecisionWoW/issues?q=scholomance
