### ISSUE TITLE
[Quest] Voodoo Feathers - reward missing

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#20]
When a player turns in the Sunken Temple warrior class quest "Voodoo Feathers" at the Fallen Hero, the player and all party/raid members in 30 yd range should gain a Battle Shout buff that grants bonus attack power and lasts 15 minutes.

This is currently not implemented.

https://classic.wowhead.com/npc=7572/fallen-hero-of-the-horde
https://classic.wowhead.com/quest=8425/voodoo-feathers
https://classic.wowhead.com/spell=25101/battle-shout#comments

**Comment by Junodruid** [comment]
upvote from me.
