### ISSUE TITLE
Relocation in BGs

### ISSUE THREAD

**Issue by FidaHD** [VortexPrecision/PrecisionWoW#200]
Hello! Whenever you queue for 2 bgs at once and enter one of them. After you enter one of them and the other BG queue comes up. If you enter the other BG queue you will be wherever you were in the first BG. I will simplifiy it, example:

You queue for 2 bgs.
Warsong Gulch comes up and you enter. You move to the other base.
Arathi Basin comes up and you click enter. You will be wherever you were in the other BG. Sometimes this can clip you under the ground or in groups I think.

**Comment by VortexPrecision** [comment]
fixed
