### ISSUE TITLE
[Quest] Wanted - Deathclasp, Terror of the Sands

### ISSUE THREAD

**Issue by supmonkas** [VortexPrecision/PrecisionWoW#201]
This quest is not appearing at the wanted poster in Cenarion Hold, Silithus, I spoke with a GM and they said that the NPC for the quest is spawned, but that they could not see the quest either.

**Comment by awatenn** [comment]
Quest is supposed to be unavailable until AQ patch.

**Comment by VortexPrecision** [comment]
> Quest is supposed to be unavailable until AQ patch.

^
