### ISSUE TITLE
[Ability] Rake

### ISSUE THREAD

**Issue by Gubbyfishy** [VortexPrecision/PrecisionWoW#209]
Initial damage portion does Physical damage instead of Bleed, and is therefore unintentionally affected by reduction from armor.

Kind regards.

**Comment by VortexPrecision** [comment]
"visuals/misunderstanding, as both parts shows in combat log as Physical and both affected by warriors Blood Frenzy/Trauma effects (4% physical damage/30% bleed damage increase)
41×1.04×1.3~=55.4 and 226×1.04×1.3~=305.5"

![image](https://user-images.githubusercontent.com/71529592/133946638-70b16f78-a55a-481e-bb18-6ef16c2e3372.png)
