### ISSUE TITLE
Warrior Charge still bugged

### ISSUE THREAD

**Issue by mariobrose2** [VortexPrecision/PrecisionWoW#213]
Charging anywhere as a warrior is still causing issues, you get DCed everytime, even when you charge in flat terrain please fix asap its too annoying to play.

**Comment by VortexPrecision** [comment]
I can't really get DC by charging. How many ms you have when you're playing here?

**Comment by mariobrose2** [comment]
I have 200 ms, it happens very rarely but sometimes you can have it occur 3 times in a row which is pretty annoying. Don't know how to reproduce it it just feels so random but the bug is still there...

**Comment by TheRealestMcCoy** [comment]
I did a charge in water one time and got a DC. Thought it was a server crash but was able to log right back in. My issue happened at low level in Elwynn Forrest doing the kelp from the murlocs. Other than that 1 time I haven't had it no more
