### ISSUE TITLE
[AV] Quest Checking

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#217]
Based on:
https://classic.wowhead.com/guides/alterac-valley-quests-pvp-battleground-classic-wow

Horde:

- [x]  The Battle for Alterac (+500 reputation)
- [x]  The Eye of Command (+500 reputation)
- [x]  Legendary Heroes (+500 reputation)
- [x]  Earned Reverence (+350 reputation)
- [x]  Invaders of Alterac Valley (+350 reputation)
- [x]  Brotherly Love (+250 reputation)
- [x]  Capture a Mine (+250 reputation)
- [x]  Defusing the Threat (+250 reputation)
- [x]  Enemy Booty (+250 reputation)
- [x]  Fallen Sky Lords (+250 reputation)
- [x]  Honored Amongst the Clan (+250 reputation)
- [x]  In Defense of Frostwolf (+250 reputation)
- [x]  Proving Grounds (+250 reputation)
- [x]  Rise and Be Recognized (+250 reputation)
- [x]  The Graveyards of Alterac (+250 reputation)
- [x]  Towers and Bunkers (+250 reputation)
- [x]  Zinfizzlex's Portable Shredder Unit (+25 reputation)
- [x]  Speak with our Quartermaster (+10 reputation)

Alliance:

- [x]  The Battle of Alterac (+500 reputation)
- [x]  The Eye of Command (+500 reputation)
- [x]  Legendary Heroes (+500 reputation)
- [x]  Earned Reverence (+350 reputation)
- [x]  Invaders of Alterac Valley (+350 reputation)
- [x]  Brotherly Love (+250 reputation)
- [x]  Capture a Mine (+250 reputation)
- [x]  Defusing the Threat (+250 reputation)
- [x]  Armor Scraps (+250 reputation)
- [x]  Fallen Sky Lords (+250 reputation)
- [x]  Honored Amongst the Guard (+250 reputation)
- [x]  The Sovereign Imperative (+250 reputation)
- [x]  Rise and Be Recognized (+250 reputation)
- [x]  Proving Grounds (+250 reputation)
- [x]  Alterac Valley Graveyards (+250 reputation)
- [x]  Towers and Bunkers (+250 reputation)
- [x]  Zinfizzlex's Portable Shredder Unit (+25 reputation)
- [x]  The Quartermaster (+10 reputation)

**Comment by PrecisionWisy** [comment]
For Alliance side:

The Battle of Alterac: Doesn't get completed after killing Drek'Thar
The Eye of Command: NPC doesn't give the quest.
Legendary Heroes: 700 Reputation
Earned Reverence: 490 Reputation
Invaders of Alterac Valley: Alliance version is "Remember Alterac Valley!": 210 Reputation
Brotherly Love: NPC not there?
Capture a Mine: 350 Reputation
Defusing the Threat: NPC not there?
Armor Scraps: 350 Reputation
Fallen Sky Lords: NPC not there?
Honored Amongst the Guard: 350 Reputation
The Sovereign Imperative: 350 Reputation
Rise and Be Recognized: 350 Reputation
Proving Grounds: 350 Reputation
Alterac Valley Graveyards: 350 Reputation
Towers and Bunkers: 350 Reputation
Zinfizzlex's Portable Shredder Unit: NPC not there?
The Quartermaster: 14 Reputation

Edit:
All missing NPCs have been added.
Brotherly Love: NPC doesn't give the quest.
Defusing the Threat: 350 Reputation
Fallen Sky Lords: NPC doesn't give the quest.
Zinfizzlex's Portable Shredder Unit: https://github.com/VortexPrecision/PrecisionWoW/issues/376

**Comment by PrecisionWisy** [comment]
For Horde Side:

The Battle for Alterac: 280 Reputation
The Eye of Command: 700 Reputation
Legendary Heroes: 700 Reputation
Earned Reverence: 490 Reputation
Invaders of Alterac Valley: 210 Reputation
Brotherly Love: NPC doesn't give the quest.
Capture a Mine: 350 Reputation
Defusing the Threat: 350 Reputation
Enemy Booty: 140 Reputation
Fallen Sky Lords: NPC doesn't give the quest.
Honored Amongst the Clan: 350 Reputation
In Defense of Frostwolf: 350 Reputation
Proving Grounds: 140 Reputation
Rise and Be Recognized: 350 Reputation
The Graveyards of Alterac: 350 Reputation
Towers and Bunkers: 350 Reputation
Zinfizzlex's Portable Shredder Unit: https://github.com/VortexPrecision/PrecisionWoW/issues/376
Speak with our Quartermaster: 14 Reputation

**Comment by PrecisionWisy** [comment]
https://github.com/VortexPrecision/PrecisionWoW/issues/376
https://github.com/VortexPrecision/PrecisionWoW/issues/377
