### ISSUE TITLE
Chests

### ISSUE THREAD

**Issue by 11011010** [VortexPrecision/PrecisionWoW#219]
![image](https://user-images.githubusercontent.com/69040574/103091294-c5f65200-4604-11eb-8c9d-1b64e8e9be2d.png)
they have no loot and do not despawn.

**Comment by awatenn** [comment]
a possible cause for this issue could be that someone opens chest while in a group and has to roll for an item. if you abandon the chest before the loot roll finishes the loot inside chest is gone, yet the chest remains. usually the player inside group can open the chest again after roll finishes (without loot) and the chest will despawn, but if someone from outside the group tries to loot the chest while empty now, it will bug out and not despawn. possible fix for these chests could be to make them exempt from being affected by party loot rolling

**Comment by VortexPrecision** [comment]
https://github.com/TrinityCore/TrinityCore/issues/12539

**Comment by VortexPrecision** [comment]
fixed recently
