### ISSUE TITLE
Death Knight - First Aid not working

### ISSUE THREAD

**Issue by Hygnxx** [VortexPrecision/PrecisionWoW#221]
As a Death Knight, I can learn First Aid but when I click it in my spellbook nothing happens.

**Comment by Hygnxx** [comment]
Thank You! I was able to get into my Fist Aid and begin training. Unfortunately I tried to learn Journeyman First Aid 'while making linen bandages'. I clicked on the link to learn it and it disapperared and I am unable to learn it now. 
![WoWScrnShot_122620_174616](https://user-images.githubusercontent.com/60664006/103161662-751c6000-47a2-11eb-9657-e4f0b00877ae.jpg)

**Comment by VortexPrecision** [comment]
> Thank You! I was able to get into my Fist Aid and begin training. Unfortunately I tried to learn Journeyman First Aid 'while making linen bandages'. I clicked on the link to learn it and it disapperared and I am unable to learn it now.
> ![WoWScrnShot_122620_174616](https://user-images.githubusercontent.com/60664006/103161662-751c6000-47a2-11eb-9657-e4f0b00877ae.jpg)

Alright thanks for the report again, i am going to verify.

**Comment by Hygnxx** [comment]
The original DK specific issue was resolved.
