### ISSUE TITLE
[Alliance Quest] Recover the Cargo! nothing happens when you use Salvage Kit

### ISSUE THREAD

**Issue by sulo251** [VortexPrecision/PrecisionWoW#223]
The quest Recover the Cargo! requires you to obtain 6 Salvaged Strongbox from the Shipwrecked Debris using the Salvage Kit provided by the NPC Renn McGill. However when you use the Salvage Kit near the Shiprecked Debris nothing happens. I tried multiple debris and multiple angle.

**Comment by nunopiri** [comment]
Can confirm
