### ISSUE TITLE
Nightbane Shadow Weavers (mobs) missing in Duskwood

### ISSUE THREAD

**Issue by nunopiri** [VortexPrecision/PrecisionWoW#225]
As the title says these mobs are not where they should be.

https://classic.wowhead.com/npc=533/nightbane-shadow-weaver

These mobs are needed to be able to complete this quest:
https://classic.wowhead.com/quest=173/worgen-in-the-woods

**Comment by VortexPrecision** [comment]
They are there

![image](https://user-images.githubusercontent.com/71529592/103160033-53ce6a80-47c8-11eb-9a1e-28064ceebad7.png)

this was fixed some weeks ago, when their respawn time was 7 days for some reason.
