### ISSUE TITLE
Stables keep consuming pets.

### ISSUE THREAD

**Issue by notJunior** [VortexPrecision/PrecisionWoW#227]
Pets keep disappearing whenever you put them into stables. They show up as invisible, as if you don't have the pet (despite it being summoned right next to you) and once you deposit it to stables, it's forever gone. Lost 3 turtles this way. Happens both by using Call Stabled Pet and Stables NPC.

**Comment by VortexPrecision** [comment]
guide me with steps how to reproduce this bug please. thank you.
