### ISSUE TITLE
[Scholomance] Vectus

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#230]
Has no loot.

**Comment by awatenn** [comment]
Vectus is supposed to have 100% drop for green-quality scourgestone if you have the Argent Dawn Commendation equipped, but he is not guaranteed to drop a blue item (at least in Classic)

**Comment by VortexPrecision** [comment]
> Vectus is supposed to have 100% drop for green-quality scourgestone if you have the Argent Dawn Commendation equipped, but he is not guaranteed to drop a blue item (at least in Classic)

and if you don't meet any of those conditions? doesn't drop anything?
