### ISSUE TITLE
fire resistance 

### ISSUE THREAD

**Issue by Takachaeng** [VortexPrecision/PrecisionWoW#238]
Fire resistance gear doesn't mitigate fire dmg

Had 1 tank on ragnaros with 315 FR and he got hit for over 10k

**Comment by valens14** [comment]
To clarify from what I heard happened in their run (I was not in this one so I could be wrong) it was the critical hits that were not mitigated.  AFAIK non critical damage is being mitigated properly by resistance.

**Comment by Takachaeng** [comment]
shouldn't it mitigate it anyway since it was a fire attack?

**Comment by valens14** [comment]
Yes both critical and non critical hits should be mitigated by fire resistance.

**Comment by VortexPrecision** [comment]
This is WOTLK resistance mechanic. it's different from vanilla.

**Comment by Takachaeng** [comment]
Thanks for pointing that out Vortex. In that case resistance mitigates a small portion of the elemental damage

Found a mitigation table for wotlk which seem correct
10% 45 57
15% 71 90
20% 100 128
25% 134 170
30% 172 219
35% 216 275
40% 267 340
45% 328 418
50% 400 510
55% 489 624
60% 600 765
