### ISSUE TITLE
Nelson the Nice - Hunter quest

### ISSUE THREAD

**Issue by Derken123** [VortexPrecision/PrecisionWoW#242]
I can't talk to "Nelson The Nice" to turn him into a demon. I can only attack him, even if he appears neutral to me. If I try to attack him in his "human form", he kills me in one hit (over 6k + damage).

**Comment by VortexPrecision** [comment]
he is supposed to kill you if you try to attack him in human form, that's normal. and i think you have to relog to be able to talk to him again because you toggle "at war" with his faction at the moment you attack him.

**Comment by VortexPrecision** [comment]
fixed recently by changing it to friendly.
