### ISSUE TITLE
Gnomish Battle Chicken does not attack properly and does not apply 5% haste

### ISSUE THREAD

**Issue by Chad-CL** [VortexPrecision/PrecisionWoW#245]
Gnomish Battle Chicken does not "Battle Squawk" to provide 5% melee haste to the party. It does enrage, but nothing else.

https://classic.wowhead.com/item=10725/gnomish-battle-chicken#comments

**Comment by Chad-CL** [comment]
This melee haste should stack with all other buffs and be activated when it attacks things.

**Comment by 11011010** [comment]
It 3.3 5 client it does not. Not a bug

**Comment by Chad-CL** [comment]
https://www.mmo-champion.com/threads/1096942-Guide-How-to-get-5-Melee-Haste-for-4Minutes

This post discusses battle chicken giving 5% haste in dragonsoul cataclysm.

**Comment by 11011010** [comment]
Still against adding it again. There are already enough balance things going on.

**Comment by Chad-CL** [comment]
![image](https://user-images.githubusercontent.com/32410028/103464500-f74bdd80-4ce8-11eb-8b6a-6080e53492b7.png)

Patch 3.3.2

**Comment by Chad-CL** [comment]
![image](https://user-images.githubusercontent.com/32410028/103464518-15b1d900-4ce9-11eb-9eb6-bc5720a8b0b4.png)

Commenter saying that it procs only on party members, patch 3.1.3

**Comment by Chad-CL** [comment]
And I understand the hesitation of using non WOTLK patch comments but the reason I'm pasting 7.2.5 is to say that the ability is IN the game.

![image](https://user-images.githubusercontent.com/32410028/103464560-79d49d00-4ce9-11eb-8e4f-77deb1648e27.png)

**Comment by Chad-CL** [comment]
> Still against adding it again. There are already enough balance things going on.

If this is the reason against adding the pet haste, fine. But please swap my engineering specialization to goblin when you have the chance.
