### ISSUE TITLE
Issue item ID: 19066 (Warsong Gulch Runecloth Bandage)

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#247]
_1. BG reputation bandages does not cause a debuff so they can be spammed.

2. The bandage can not be used when fighting for the opposite faction (sometimes?), other bg reputation items bugs out as well when being crossfaction. For example Item ID: 20071 (Talisman of Arathor) can not be used when fighting for the other faction and also can not be equipped mid bg.

I assume the bandage issue is on all bg rep bandages_

In-game ticket by Nottin

**Comment by Broker-Precision** [comment]
Recently bandaged debuff is applying to player.

**Comment by VortexPrecision** [comment]
Old ticket, these have been fixed.
