### ISSUE TITLE
Hunter pets don't keep their health after mounting

### ISSUE THREAD

**Issue by kotomaxibon** [VortexPrecision/PrecisionWoW#249]
Title. After a hunter mounts the pet gets healed to full. Supposed to keep his health. (Possible same with warlocks, haven't tested)

**Comment by VortexPrecision** [comment]
Source that this is not blizzlike? Because afaik this is blizzlike.

**Comment by 11011010** [comment]
I think the same, it is blizzlike.

**Comment by kotomaxibon** [comment]
Saw multiple people report that in discord so i assumed it's a bug. Closing the issue.
