### ISSUE TITLE
Solid chests in winterspring broken

### ISSUE THREAD

**Issue by raltasha** [VortexPrecision/PrecisionWoW#259]
Two Solid Chests are broken since forever. Restarts, Resets or whatever there is dont seem to fix them.

This is when you enter Winterspring from the westside. Marked on this Screenshot https://i.imgur.com/1V8Nblv.png.

**Comment by Broker-Precision** [comment]
Unable to reproduce, Can you confirm this ois still an issue?

**Comment by Broker-Precision** [comment]
Confirmed no issue on live realm.
