### ISSUE TITLE
Threat mechanics

### ISSUE THREAD

**Issue by cts17** [VortexPrecision/PrecisionWoW#262]
Threat generation on this server is whack.

Swipe does very little threat, Maul does 3x the threat of everything else, Hammer of the Righteous does a lot of threat. 

No experience with DKs, but threat generation is something like

Warrior: 1x
Paladin: 2x warrior
Druid: 3x Paladin, 6x Warrior

**Comment by Broker-Precision** [comment]
Various improvements have been implemented for each class. See ChangeLog on discord for more infomation.

**Comment by Broker-Precision** [comment]
Going to close this Ticket, if threat becomes an issue again please post another ticket.
