### ISSUE TITLE
Hunter dead zone seems off

### ISSUE THREAD

**Issue by 11011010** [VortexPrecision/PrecisionWoW#263]
The Hunter dead zone is less then it should be. A good indicator of it working correctly is:

 when as a hunter when you have aggro from a mob and it is in melee range and does not have a slow on it, it should not be possible to use your bow/ranged ability even when you run. Only after you slow it you can get into bow range!

**Comment by VortexPrecision** [comment]
tested by a hunter expert confirmed this as invalid.
