### ISSUE TITLE
[Consumables] Mana Potions sharing CD with Demonic Runes/Dark Runes/Night Dragon's Breath

### ISSUE THREAD

**Issue by Sssanctify** [VortexPrecision/PrecisionWoW#268]
Once the player enters combat, the game only allows the usage of one of the consumables mentioned on the title. As far as I've researched, you should be able to use Mana Potion + Any one of those before triggering their cooldowns. 

What happens now is: You use the consumable and, although on the tooltip of the others doesn't show a Cooldown countage, you receive a message of "I can't drink that now". On the other hand, **If you're out of combat** , everything work normally.

**Comment by VortexPrecision** [comment]
are you sure this is not intended on WOTLK mechanics? Also, please mention the source for the bug report.

**Comment by Sssanctify** [comment]
I'm sorry. I'm sure they should work like that on Vanilla but I always forget that the client is 3.3.5. I still couldn't find a proper source on how the cooldowns should work between themselves but now I feel that is probably just some change along the patches.

**Comment by Sssanctify** [comment]
I'm sorry. I'm sure they should work like that on Vanilla but still couldn't find a source on how the cooldowns worked betweem themselves on 3.3.5. Altho, of one thing I'm positive: On my first raid on the server Demonic Runes had 2 minutes cooldown and were able to be used just like on regular Vanilla. After some update or something, they changed to 15 minutes cooldown and started to share CDs. Anyway, if its intended, its ok. I just wanted to be sure of it =)

**Comment by VortexPrecision** [comment]
I suspect this is correct for 3.3.5a mechanics, but i don't have time rn to try to find the source so i was hoping you could check and confirm it.

**Comment by Sssanctify** [comment]
I finally figured it out. 
1- Demonic Runes are working as intended. 15 minutes CD and sharing this CD with Night Dragon's Breath but not with Mana Potions. The thing that surprised me was the upgrade on the CD from 2 minutes to 15, but that is confirmed to be the case on 3.3.5 clients (Altho i can't explain why it wasn't working like that on the start of the server).
2- Night Dragon's Breath is the one with a problem. It's counting as a Mana Potion when it shouldn't. When you use it in combat, and then try to use a Mana Potion, your character reacts like if you *already* used a Mana Potion and its trying to use another one. That is what shouldn't  be happening. You should be able to use 1 Night Dragon's and 1 Mana Potion right after.
3- My PC is too crappy to make a video showing the problem but i can try later if its necessary

https://wotlk.evowow.com/?item=11952#shared-cooldown

**Comment by Broker-Precision** [comment]
Corrected shared cooldowns for Night Draon's Breath as per shared cooldowns in source: https://classic.wowhead.com/item=11952/night-dragons-breath#shared-cooldown

Now Night Dragon's Breath & Dark Rune share a cooldown, However a mana potion such as Super Mana potion will not go on cooldown
