### ISSUE TITLE
Custom tmog item not working

### ISSUE THREAD

**Issue by beebeebeebb** [VortexPrecision/PrecisionWoW#272]
I bought a [transmog : shadow occult - Cloak] but its not showing up in the menu to add it to my tmog list
only other cloaks  I have in my bag showed up
![J3ZNls](https://user-images.githubusercontent.com/76980529/103596704-210d2c00-4ec4-11eb-85a4-1a086629aa37.jpg)

**Comment by VortexPrecision** [comment]
fixed
