### ISSUE TITLE
cannot loot mount in Satchel of special goods

### ISSUE THREAD

**Issue by Derken123** [VortexPrecision/PrecisionWoW#276]
my satchel of special goods seems buggy. I can't loot the mount even if I try to relog.
![WoWScrnShot_010521_173616](https://user-images.githubusercontent.com/76665443/103707667-0e0a6280-4f7d-11eb-92d1-5374bfec47b0.jpg)

**Comment by Derken123** [comment]
I have tried disabling addons. The mount is still in the bag, but I still can't loot it.
![WoWScrnShot_010521_174426](https://user-images.githubusercontent.com/76665443/103708006-b1f40e00-4f7d-11eb-8806-0469308d2508.jpg)

**Comment by Derken123** [comment]
I just had a 2nd Satchel of special goods which gives me the same bug but with a different mount this time. Is there a way to fix this?
![WoWScrnShot_010621_182412](https://user-images.githubusercontent.com/76665443/103832608-ad4a5b00-504c-11eb-8298-a6b88ece7d1c.jpg)

**Comment by VortexPrecision** [comment]
seems to be a client issue. will check your character

**Comment by VortexPrecision** [comment]
yes, client issue 100%
![image](https://user-images.githubusercontent.com/71529592/103841937-9592c700-508c-11eb-9ea7-e8425e6f4d6c.png)

**Comment by Derken123** [comment]
Nice! thank you so much. Do I have to reinstall the client to avoid this bug again?

**Comment by VortexPrecision** [comment]
> Nice! thank you so much. Do I have to reinstall the client to avoid this bug again?

i recommend you do it because i was able to open on my client perfectly and looking at your screenshots you have some weird invisible slots on the bag loot, that is not normal.
