### ISSUE TITLE
Skinning 

### ISSUE THREAD

**Issue by Bishooi** [VortexPrecision/PrecisionWoW#277]
Hi my name is bishop in game so I leveled up 300 skinning and realized that you need more skinning to skin stuff such as onyxia to do that you need a gloves Ench also to equip finkles which is a dagger and I can’t equip it because of class was hoping for maybe to tune down skinning requirement for now and or when you have finkles in your bag to allow the skinning buff to work as if it was equiped

**Comment by Broker-Precision** [comment]
Hi, Unfortunately this is blizlike, However you'll be able to get https://classic.wowhead.com/item=19901/zulian-slicer once ZG is open. This is the equilivant of the dagger, for other classes.
