### ISSUE TITLE
[Quest] Furlbrow's Deed

### ISSUE THREAD

**Issue by snowflake-fr** [VortexPrecision/PrecisionWoW#278]
I think there is something wrong with the droprate of the item "Westfall Deed" which allows to start the quest "Furlbrow's Deed". 

I farmed a lot of the following NPCs : Defias Bodyguard, Defias Dockmaster, Defis Bandit, Defias Dockworker, Defias Rogue Wizard, the item never dropped.

**Comment by Broker-Precision** [comment]
Corrected loot drop rate for item "Westfall Deed". As per values from https://classic.wowhead.com/item=1972/westfall-deed
