### ISSUE TITLE
[Quest] The Collector

### ISSUE THREAD

**Issue by snowflake-fr** [VortexPrecision/PrecisionWoW#279]
I think there is something wrong with the droprate of the item "Gold Pickup Schedule" which allows to start the quest "The Collector".

I farmed a lot of the following NPCs : Riverpaw Runt, Riverpaw Outrunner, Hogger, the item never dropped.

Plus, I think Gruff Swifbite is not implemented on the server whereas he drops the item 87% of the time.

**Comment by Broker-Precision** [comment]
Corrected drop rates from NPCs : Riverpaw Runt, Riverpaw Outrunner, Hogger.
Confirmed Gruff Swifbite is spawnable.
