### ISSUE TITLE
Drefge Striker mobs give light leather from skinning it

### ISSUE THREAD

**Issue by Crusherxxx** [VortexPrecision/PrecisionWoW#280]
when i skinning  Drefge Striker  mobs in silithus its drop light leather where should drop  Rugged Leather

https://classicdb.ch/?npc=11740#skinning
https://www.wowhead.com/npc=11740/dredge-striker#skinning

**Comment by awatenn** [comment]
Dredge Strikers and Dredge Crushers should not be skinnable at all, this was changed in Cataclysm to give Rugged Leather. You can check Classic Wowhead to see these mobs are not skinnable.
https://classic.wowhead.com/npc=11740/dredge-striker

**Comment by VortexPrecision** [comment]
he is right, not skinnable on classic wowhead
https://classic.wowhead.com/npc=11740/dredge-striker#skinning
