### ISSUE TITLE
[Quest] Captain Sander's Hidden Treasure

### ISSUE THREAD

**Issue by snowflake-fr** [VortexPrecision/PrecisionWoW#283]
I think there is something wrong with the droprate of the item "Captain Sander's Treasure Map" which allows to start the quest "Captain Sander's Hidden Treasure".

I farmed a lot of NPCs, the item never dropped.

**Comment by Broker-Precision** [comment]
Corrected drop % rates as per https://classic.wowhead.com/item=1357/captain-sanders-treasure-map
