### ISSUE TITLE
Death on Feralas ship

### ISSUE THREAD

**Issue by nunopiri** [VortexPrecision/PrecisionWoW#286]
On the ship from Feathermoon Stronghold to the mainland if you go on the lowest part of the ship you face certain death a bit before arriving at the mainland peer.

**Comment by alydevs** [comment]
+1, i was on top of the boat, as it started turning to come to the mainland dock I suddenly took fatal fall damage

**Comment by VortexPrecision** [comment]
Cannot reproduce, must have been problem related to older maps, they have been replaced and it doesn't happen again (just tested).
