### ISSUE TITLE
[ZG] Raid Review

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#293]
- [x] Gurubashi bat riders shouldn't be stunnable
- [x] Axe throwing not doing their AOE and doesn't knock back on axe throw. (they do the AOE)
- [x] loot needs review
- [x] Vodoo slave doesn't summon infernals
- [x] Shadow hunters aren't multishooting

**Jin'do the Hexxer**

- [x] Hex doesn't drop threat
- [x] teleporting MCed people

**Hakkar**

- [x] Should reset if you move him out of the platform
- [x] Too much loot
- [x] Each priest alive should give 20% more hp.

- [x] druids cant use rogue zg items
- [x] Reviewed all Main bosses (not optional) loot 
- [x] Some items are still locked on Patch Level - To be discussed

**Comment by mchayes** [comment]
Issues regarding Heart of Hakkar buff;
- Is currently not applied to players/npc in Booty Bay,
- Is removed upon death.

Not sure which patch we are supposed to be in but people _should_ get the buff in booty bay, and it _shouldn't_ be removed when dying. At least in early blizzlike wow.

Comment string on wowhead, scroll down https://classic.wowhead.com/spell=24425/spirit-of-zandalar#comments

**Comment by mchayes** [comment]
Same applies for the Zanza potions, Spirit - Sheen - Swiftness. They either exist where;
- They are not removed upon death _&_ are unique, or;
- They are removed upon death _&_ are stackable(not unique).

Currently they _are_ unique and _are_ removed upon death. This was never _both_ a thing in a blizzlike situation.
https://classic.wowhead.com/item=20081/swiftness-of-zanza#comments
https://classic.wowhead.com/item=20079/spirit-of-zanza#comments
https://classic.wowhead.com/item=20080/sheen-of-zanza#comments

**Comment by VortexPrecision** [comment]
> Issues regarding Heart of Hakkar buff;
> 
> * Is currently not applied to players/npc in Booty Bay,
> * Is removed upon death.
> 
> Not sure which patch we are supposed to be in but people _should_ get the buff in booty bay, and it _shouldn't_ be removed when dying. At least in early blizzlike wow.
> 
> Comment string on wowhead, scroll down https://classic.wowhead.com/spell=24425/spirit-of-zandalar#comments

the persist through death sounds like a bug and that comment sounds like they fixed it.

**Comment by mchayes** [comment]
what

**Comment by VortexPrecision** [comment]
yes it was changed, doesn't mean it was intentional from the beginning, blizz did many mistakes back then and had many issues and bugs that were fixed along the way. Not sure if it's a good idea to make it work that way.
