### ISSUE TITLE
Potential bug for Druid Sea lion quest.

### ISSUE THREAD

**Issue by avalpreda** [VortexPrecision/PrecisionWoW#295]
As the title says, I think there is a bug with the sea lion quest.  As a night elf, the map showed I needed to get the pendant of Endurance from the ocean near silverpine.  However, the pendant was in Westfall.

Screenshots attached.
![2021-01-14 (2)](https://user-images.githubusercontent.com/77474791/104677850-2fbfc400-56b8-11eb-8157-c32eda87f369.png)
![2021-01-14](https://user-images.githubusercontent.com/77474791/104677853-31898780-56b8-11eb-8b23-17c265d2a3b9.png)
![2021-01-14 (1)](https://user-images.githubusercontent.com/77474791/104677854-32bab480-56b8-11eb-91d3-f6fcdef56c67.png)

**Comment by Broker-Precision** [comment]
Made some POI improvements.
