### ISSUE TITLE
Bug with Onyxia’s fear

### ISSUE THREAD

**Issue by Kaptajnu** [VortexPrecision/PrecisionWoW#299]
During my last Onyxia raid I noticed that after using a Major Mana Potion it says it will reset it’s Cooldown after combat. Yet everytime Onyxia used her Fear in phase 3 it seemed to reset the combat effect on the Major Mana Potion and made the Cooldown only a minute again, as if I had left combat when the fear hit. This enabled me to apparently chug Major Mana Potions during the entire phase 3 which seems very unintended. 

This could also be the case with other fears as on Magmadar but I can’t be certain since I didn’t notice nor test it then.

Please let me know if it’s on purpose or unintended. Thanks!

**Comment by VortexPrecision** [comment]
It's unintended

**Comment by VortexPrecision** [comment]
fixed
