### ISSUE TITLE
Tribute loot

### ISSUE THREAD

**Issue by WavyCrocket** [VortexPrecision/PrecisionWoW#302]
After killing the King at the end of DMN, should Kromcrush become available to talk to so as to get the 3rd rare item in the tribute chest? As of right now he is not.

**Comment by mchayes** [comment]
You need to get the king buff, then talk, then spawn chest.

**Comment by VortexPrecision** [comment]
> You need to get the king buff, then talk, then spawn chest.

this. not a bug.
