### ISSUE TITLE
Quest -- The Shade of Elura

### ISSUE THREAD

**Issue by Velthur-bot-3000** [VortexPrecision/PrecisionWoW#303]
Warrior Quest -- The Shade of Elura   
questID:  1686
Crate of Elunite ID: 86492

Quest in itself, it seems that the box placements for the ore are off in vmap or just coords in general.  You will see glimmer like there is a box but its too far underground that you can't click it.  Can complete the quest currently, just takes some waiting for respawns instead of being able to locate and find all 8 crates of ore easily.

Also seems their loot table is off, should also have very small chances to drop trash items.

https://classic.wowhead.com/quest=1686/the-shade-of-elura
https://classic.wowhead.com/object=86492/crate-of-elunite

**Comment by Broker-Precision** [comment]
I've corrected the boxes that spawned under ground.
Correct trash loot drop from crate of elunite
