### ISSUE TITLE
Rune of the Dawn - and others

### ISSUE THREAD

**Issue by mchayes** [VortexPrecision/PrecisionWoW#304]
Currently the following item does not grant _any_ extra damage when fighting undeads. 
![image](https://user-images.githubusercontent.com/20542656/105161000-2c419800-5b11-11eb-8618-5aabc8c9667b.png)

It is likely that of the same types of items none work. AP version or Argent Avenger per example.

**Comment by mchayes** [comment]
the attack power one does seem to work, according to PTR. dunno about live

spelldmg still _not_ working on live

**Comment by VortexPrecision** [comment]
Fixed recently.
