### ISSUE TITLE
Quest -- Hilary's Necklace

### ISSUE THREAD

**Issue by Velthur-bot-3000** [VortexPrecision/PrecisionWoW#306]
QuestID -- 3741
https://classic.wowhead.com/quest=3741/hilarys-necklace

So, I looted the "Glinting Pile of Mud" and it said I was too far away.  So I moved closer and now it just says the item is in use and I cannot loot it currently.  Waiting to see if it will reset so I can re loot and get item.  will update.

update, after waiting about 5-10 minutes, the pile of mud reset/allowed me to loot it.

**Comment by Broker-Precision** [comment]
Hello, This is an common bug, I believe this was an issue on retail as well, However I could be wrong about that. As of now the only fix is to wait for the object to reset. However if an object doesnt reset in 5-10 minutes please let us know.
