### ISSUE TITLE
DK Blood Tank threat & Co.

### ISSUE THREAD

**Issue by Penthax** [VortexPrecision/PrecisionWoW#308]
Good Evening,

In my Opinion DK Tanks are the worst at the moment, they dont have any Damage Reduc. Cooldowns, so they are also bad when you fight against Bosses/Mobs with heal reduc. Debuffs, Vampiric Blood dont help much against this.

- Threat is also a Problem if you try to tank an Mobpack, Death and Decay do alot of lesser threat then other Tank Class aoe Spells... it also scale like nothing. Naked it does like 45 Damage..full geared it does around 50.. so not a big difference for 300-400 AP and around 110 STR.

- Dks also lack on Relics / Sets and also Sets with Setbonus, Warrior Set is not that bad, but yea..

**Comment by Penthax** [comment]
Dont want to make a new Post for it : 

- Can you change that Bloodworms are on Neutral ? they are one aggressive and pull/attack  everything around you.

**Comment by Broker-Precision** [comment]
We most likely won't change core mechanics unless they're broken to begin with, So changing bloodworms to neutral is a no-go for now.
What would your standard rotation or spell priority when engaging into a mutli mob pack?

**Comment by Broker-Precision** [comment]
Improvements have been made to DK threat, I'll be closing this ticket. If there is huge issues please raise another ticket with details.
