### ISSUE TITLE
WIntersaber peeps are at war and you can't get the rep to turn it off

### ISSUE THREAD

**Issue by whieban** [VortexPrecision/PrecisionWoW#309]
![image](https://user-images.githubusercontent.com/77094224/105614937-ec391a00-5d89-11eb-9d49-d9014d97beb3.png)

**Comment by Broker-Precision** [comment]
Hello, II'm unable to recreate this issue, I'm neutral with them by default, Would you be able to make a ticket ingame so we can investigate this more for you're specific character?

**Comment by Broker-Precision** [comment]
Issue resolved ingame.
