### ISSUE TITLE
Darkmoon Faire Dense Grinding Stones quest

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#310]
According to Wowhead, you should be able to turn in Dense Grinding Stones at any point if you have the correct minimum level, but here you can no longer turn in any more items for some reason. It stopped showing the quest for me when I reached 2500/6000 reputation with Darkmoon Faire. There is no way for me to get enough tickets for the Necklace rewards now.

https://wotlk.evowow.com/?quest=7939
https://classic.wowhead.com/quest=7939/more-dense-grinding-stones#comments
Dense Grinding Stone:
1920 Dense Stone = 480 Dense Grinding Stone = 1200 Ticket's
(Made by Blacksmith's)

These are just the main things I am going to turn in, I didn't want to waste my doing the math for all the other ones. These are the correct Number's, So there is no reason to second guess it.
Also After 1.9. You do not have to have a certain profession to turn any of these in. The quests are available to ANYONE with ANY profession.

**Comment by Broker-Precision** [comment]
Correct issue with multiple Darkmoon Fair repeatable quests.
    * More Thorium Widgets
    * More Armor Kits
    * More Dense Grinding Stones
    * More Bat Eyes
    * More Glowing Scorpid Blood
All above are now no longer gated by a required reputation level, This should bring us more in line with Vanilla. Reference: https://classic.wowhead.com/guides/classic-darkmoon-faire#darkmoon-faire-tickets
Closes: https://github.com/VortexPrecision/PrecisionWoW/issues/310
