### ISSUE TITLE
NPC/Mob Spawn issues

### ISSUE THREAD

**Issue by Velthur-bot-3000** [VortexPrecision/PrecisionWoW#313]
Smott's chest, link : https://classic.wowhead.com/item=3932/smotts-chest
Kurzen's Head link : https://classic.wowhead.com/item=3615/kurzens-head

Posted in Discord about mob spawning issues:
SyrupToday at 2:21 AM
@Vortex the Elementals on Mirage ridge in Badlands haven't respawned for 2 days, similarly the Ore nodes in the whole zone also seem to have the same problem

I also encountered this same issue with Kurzen's Head quest in STV(Stranglethorn Vale) while going through the cave all mobs were there, was only one in the area leveling.  Got to the end of the cave and the mobs before Kurzen's hangout were there, mobs and Kurzen? Not there.  Waited about 5-10 for repawns before, tried killing 2 more for previous pack and turned around to find everything spawned again.

Smott's chest not so lucky, he like the mobs in badlands has not been there for at least 2 days.  Heard reports from other players saying he simply, most of the time, isn't there.  It would seem that there are global issues with respawn/spawning of quest mobs.

**Comment by VortexPrecision** [comment]
fixed recently
