### ISSUE TITLE
massacre at lights point low/no spawn rate 

### ISSUE THREAD

**Issue by dvd1310** [VortexPrecision/PrecisionWoW#314]
Mobs sometimes do not spawn when doing the quest. on first try no one spawned in. The next day I abondoned and re-accepted the quest and saw people all the way in the back towards the cliff. I switched boats and killed about 20 when they stopped respawning. I believe they are supposed to spawn in the hole area and have a much higher respawn time. 

![WoWScrnShot_012721_193541](https://user-images.githubusercontent.com/63548790/106073250-aeb0f580-60d7-11eb-8d18-26f272f4eef3.jpg)

**Comment by VortexPrecision** [comment]
related to 
https://github.com/VortexPrecision/PrecisionWoW/issues/313
