### ISSUE TITLE
Rivern Frostwind -- Wintersaber Trainers Dailies

### ISSUE THREAD

**Issue by Velthur-bot-3000** [VortexPrecision/PrecisionWoW#318]
It seems that Rivern Frostwind, who give out all the dailies to gain rep for the Wintersaber Trainers.  The quests he gives, atleast Frostsaber Provisions, is given as a normal quest thats repeatable, multiple times, as many times as you want.  You complete and turn in and your given the quest again.  All quests given are dailies which made this a grind( the whole point obviously is to grind it out.)

https://wotlkdb.com/?quest=4970
https://wotlkdb.com/?faction=589#quests
https://wotlkdb.com/?npc=10618

**Comment by Broker-Precision** [comment]
Quests are meant to be repeatable, However reputation rewarded was incorrect, And has been updated.
