### ISSUE TITLE
List of npc's that do not count towards the guild / character progression list on the website

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#321]
Most, if not all, of these npc's are spawned outside of the dungeon.

**Wailing Caverns**
[Boahn](https://classic.wowhead.com/npc=3672/boahn)

**Deadmines**
[Thistlenettle](https://classic.wowhead.com/npc=626/foreman-thistlenettle)

**Blackrock Depths**
[Overmaster Pyron](https://classic.wowhead.com/npc=9026/overmaster-pyron)
[Ring of Law](https://classic.wowhead.com/npc=10096/high-justice-grimstone)
[Summoner's Tomb](https://classic.wowhead.com/object=169243/chest-of-the-seven)

**Upper Blackrock Spire**
[Father Flame](https://classic.wowhead.com/object=175245/father-flame)
[Warchief Rend Blackhand](https://classic.wowhead.com/npc=10429/warchief-rend-blackhand) (Gyth works fine)

These are the ones I currently know of. I'll keep updating this list.

**Comment by Broker-Precision** [comment]
Not an issue, These mobs should not give progressive points.
