### ISSUE TITLE
[Group] Relog

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#324]
_PsychToday at 6:26 PM
if u relog u drop group/raid
raid leader reloged was dropped and no one became leader_

**Comment by Miranai** [comment]
Synergy had the same problem, we had to get out of ZG and redo the raid.

**Comment by VortexPrecision** [comment]
**Also, it's possible to be alone in a group that is not RDF.**

**Comment by VortexPrecision** [comment]
fixed recently
