### ISSUE TITLE
[Item][ZG][Profession]Formula: Brilliant Mana oil not available

### ISSUE THREAD

**Issue by Miranai** [VortexPrecision/PrecisionWoW#325]
The Vendor in Strangelthorn vale does sell it, but it says "can't retrieve information". Everything else on the vendor is ok. 
It also says its a enchant, but its a formula for Alchemy.  
Probably an oversight.

**Comment by VortexPrecision** [comment]
https://github.com/VortexPrecision/PrecisionWoW/issues/25

according to the phase locking (similar to classic wow, it's only introduced with patch 4 (AQ))
the item is locked but the formula is not.
