### ISSUE TITLE
[AQ20] General Rajaxx neutral

### ISSUE THREAD

**Issue by Anthaney** [VortexPrecision/PrecisionWoW#329]
Mob ID: npc=15341

After wiping on General Rajaxx he goes into a neutral stance where he cannot be attack. I waited 10 minutes to see if the fight reset but still nothing has happened.

Solution: Make the RP sequence forced or PH on Lieutenant General Andorov (npc=15471) to encounter General Rajaxx again. Another thing you can do is make him not aggro Andorov and have him attackable after wave phase.

**Comment by VortexPrecision** [comment]
You probably didn't wipe, for the script to consider a wipe you must be dead not only the general being killed. I just tested and when General is killed nothing else happens, but when I die or leave the raid the script resets like it should. The picture here is how it looks after wiping.

![image](https://user-images.githubusercontent.com/71529592/107860592-f2299480-6e37-11eb-82b7-b828db591eeb.png)
