### ISSUE TITLE
Quest : A collection of Heads (Zul'Gurub)

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#332]
My atlas says the heads suppose to have a 100% drop chance, but in last ZG we only had 2 heads drop.
In today's ZG we had 0 heads drop

**Comment by Broker-Precision** [comment]
Hi Mikedej,

The Atlasloot data is incorrect for the current patch. As per: https://classic.wowhead.com/quest=8201/a-collection-of-heads / https://classic.wowhead.com/item=19881/channelers-head - each boss as a 12 - 14% drop chance.
