### ISSUE TITLE
[TBC] Professions - 2.0.3

### ISSUE THREAD

**Issue by Broker-Precision** [VortexPrecision/PrecisionWoW#337]
- [x] Blacksmithing
- [x] Engineering
- [x] Jewelcrafting
- [x] Leatherworking
- [x] Tailoring
- [x] Alchemy
- [x] Enchanting
- [x] Cooking
- [x] Primal Nether - BOP until 2.4.0
- [x] Nether Vortex - BOP until 2.4.0

**Comment by VortexPrecision** [comment]
Closing due being completed.
