### ISSUE TITLE
Timed quests

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#350]
When you do a timed quest (usually escort quests) and you complete it, the timer keeps on counting down.

Note here when I say **"completed"** and not **"turned in"**

So basicly you completed it, but the game thinks you didn't.

**Comment by Broker-Precision** [comment]
Do you have a specific quest where this happened? Or all timed quests?

**Comment by VortexPrecision** [comment]
this is blizzlike behavior it seems, the timer stops counting once delivered.
