### ISSUE TITLE
Opening the Dark Portal 

### ISSUE THREAD

**Issue by cts17** [VortexPrecision/PrecisionWoW#356]
New portals keep spawning even before the last one is killed. It's supposed to have the next portal open once the elite add is dead, not on a timer.

**Comment by Broker-Precision** [comment]
Source on where the portals are not timed based?

**Comment by VortexPrecision** [comment]
> New portals keep spawning even before the last one is killed. It's supposed to have the next portal open once the elite add is dead, not on a timer.

This information is incorrect, they are kill based until portal number 6 (which is exactly when the first boss spawns) then turns time based.
