### ISSUE TITLE
Blood Tap not activating Blood Rune

### ISSUE THREAD

**Issue by cts17** [VortexPrecision/PrecisionWoW#361]
Blood Tap is not re-activating Blood Runes that are on cooldown

**Comment by Broker-Precision** [comment]
Hi, I'm unable to reproduce issue on both Test and Live realm. While Blood runes are on cooldown activiating Blood Rap will convert a blood run to a death rune that will be usable. Please reach out to me on discord if you're still facing this issue and we can investigate more.

**Comment by cts17** [comment]
Hmmm, I can't reproduce the issue on the test realm, but on live when I'm in DPS spec the tap doesn't work.
