### ISSUE TITLE
[Attunement/Quest] "The Cipher of Damnation" - Cyrukh the Firelord is invalid target

### ISSUE THREAD

**Issue by Miranai** [VortexPrecision/PrecisionWoW#362]
For the TK pre-attunement the quest "The Cipher of Damnation" is bugged. The Mob "Cryrukh the Firelord" is, when summoned with the questitem given, an "invalid Target". You can't attack him and he will not attack a player near him. 

Couldn't get a video of the summoning but the scripting/dialog looks fine to me. 
After he appears, he stands still and does nothing.  He cannot be attack nor be damaged with aoe spells.  
Error message appears: "Invalid Target"
Video: https://imgur.com/a/3BQkYWe

**Comment by Broker-Precision** [comment]
You need to speak to Oronok Torn-heart when you're ready to fight to begin the fight.
