### ISSUE TITLE
Murmur Sonic Boom too large

### ISSUE THREAD

**Issue by cts17** [VortexPrecision/PrecisionWoW#363]
Either sonic boom is too large or hitbox is too small.

I stand at maximum melee distance from boss, and as soon as DBM triggers the sonic boom I start running for the door in a straight line, but I still get blasted by the boom.

**Comment by Broker-Precision** [comment]
Duplicate issue https://github.com/VortexPrecision/PrecisionWoW/issues/355 Closeing this.
