### ISSUE TITLE
Quest: Attack on Manaforge Coruu

### ISSUE THREAD

**Issue by cts17** [VortexPrecision/PrecisionWoW#364]
Attack on Manaforge Coruu should be accessible after Shutting Down Manaforge B'naar and Measuring Warp Energies have been completed. Right now it's only accessible after "Shutting Down Manaforge Coruu" has been completed, when they should be able to be done at the same time.

**Comment by Broker-Precision** [comment]
Hi Cts17, According to wowhead comments from 2.0.6 this should be available after the quest "Shutting Down Manaforge B'naar" is completed. Reference: https://www.wowhead.com/quest=10246/attack-on-manaforge-coruu

Could you point me to a source that says "Measuring Warp Energies" is also required?

**Comment by Broker-Precision** [comment]
Following up...

**Comment by Broker-Precision** [comment]
Closing as original poster has failed to provide updates.
