### ISSUE TITLE
Quest "I'm Saved!"

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#366]
Questgiver does not want to give me this quest.

"Kristen Dipswitch"

Located Nagrand, passage to Zangramarsh

**Comment by Broker-Precision** [comment]
Fixed

**Comment by Broker-Precision** [comment]
Issue is not resolve, Once script runs NPC ("Kristen Dipswitch") will evade and reset back to original spawn point but will run through rest of her script and offer player the quest "I'm Saved!"

**Comment by VortexPrecision** [comment]
She will no longer evade very far away.
