### ISSUE TITLE
PvP stuff missing from vendors

### ISSUE THREAD

**Issue by Roided93** [VortexPrecision/PrecisionWoW#367]
Missing from Merciless Glad vendor: Merciless Glad's heavy xbow
Missing in general: PvP trinket that frees you from CC lvl 70 version
(also cloak but not sure if its on this season, for the rest i am sure)

**Comment by Broker-Precision** [comment]
Corrected crossbow & pvp trinkets, Need to look into cloaks more.

**Comment by Broker-Precision** [comment]
Cloak's corrected
