### ISSUE TITLE
Shapeshifting doesn't always clear movement impairing effects

### ISSUE THREAD

**Issue by PrecisionWisy** [VortexPrecision/PrecisionWoW#371]
Shapeshifting is supposed to free the caster from movement impairing effects (slows, roots, ...), which is not working if you use the following macro:
/cast !Tree of life

This macro should shift the druid out of the Tree of Life form and immediately back in, which works with other forms, just not with Tree of Life.

**Comment by Broker-Precision** [comment]
Hi, Does using the spell "Tree Form" outside of using a macro remove the impairing effects?

**Comment by PrecisionWisy** [comment]
Yes it does, it's just this macro that doesn't remove them, although it should.
As mentioned, this works with every other form, just not the Tree of Life.
Edit: Moonkin form also doesn't work
