### ISSUE TITLE
[Quests] Zinfizzlex's Portable Shredder Unit

### ISSUE THREAD

**Issue by PrecisionWisy** [VortexPrecision/PrecisionWoW#376]
Links to both quests (Horde and Alliance):

https://classicdb.ch/?quest=6861
https://classicdb.ch/?quest=6862

https://wotlkdb.com/?quest=6861
https://wotlkdb.com/?quest=6862

Quest NPC:

https://classicdb.ch/?npc=13377
https://wotlkdb.com/?npc=13377

Description:

- [x] 1) Currently, the NPC is hostile towards alliance.

- [ ] 2) The NPC doesn't walk to the faction's base which talked to him first.

- [x] 3) The [Steamsaw](https://classicdb.ch/?item=17411), which is a required item for the quest, is not on the map.

- [x] 4) The Shredder Unit (https://classicdb.ch/?npc=13378 for Horde and https://classicdb.ch/?npc=13416 for Alliance) doesn't have any abilities aside from normal attacks.

How it should work:
1) The NPC should be friendly towards both factions until 1 faction has talked to him, after which he becomes hostile towards the opposing faction.

2) After talking to the NPC, he should walk towards the base of the respective faction.

3) The Steamsaw should be at the Lumbermill of each faction. For the Alliance, the Steamsaw is at the Horde's Lumbermill and vice versa.

4) The Shredder Unit is supposed to have 2 abilities:

Cleave
Next Melee
Inflicts normal damage plus 180 to an enemy and its nearest allies, affecting up to 3 targets.
https://classicdb.ch/?spell=20605

Shredder Armor Melt
2 sec cast
Deals 740 to 860 Fire damage to all targets in a cone infront of the caster. Also causes 5% durability loss to the chest armor of your opponent.
https://classicdb.ch/?spell=21559

How to replicate the issue:
1) Join AV as alliance and approach the NPC.

2) Talk to the NPC.

3) Accept the quest from the NPC and look around in the opposing's faction lumbermill.

4) Take control of the Shredder Unit and watch your action bars.

**Comment by VortexPrecision** [comment]
https://classicdb.ch/?search=steamsaw#objects

**Comment by Broker-Precision** [comment]
CLosing ticket, No info found regarding item 2. Rest fixed.
