### ISSUE TITLE
DK - Wandering Plague

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#380]
one more minor udk bug, as https://wotlkdb.com/?spell=49217 appears to proc way lower than your melee crit chance
![imagem](https://user-images.githubusercontent.com/71529592/133657495-3241ab0d-7928-4758-af23-15861115b195.png)

with 100++% crit chance x)
![imagem](https://user-images.githubusercontent.com/71529592/133657509-d9aaaaa4-f5de-41a5-af46-58c9ded3ba1b.png)

420*0.258~=108 procs, I got 53, with 100+% it's even more obvious
and, worth mention, that I got almost 2+ times less proc rate on my every test, those are just pure diseases + wandering plague tests to show bug itself

**Comment by VortexPrecision** [comment]
proc chance is 2x lower than what it should be

**Comment by Broker-Precision** [comment]
Fixed internal cooldown. Previously was set to 5 secs, Changed to 1 sec. Still based on Melee crit chance.. This is still under review and might be changed if it causes issues.
