### ISSUE TITLE
Pet abilities cannot be toggled off

### ISSUE THREAD

**Issue by nightlife123** [VortexPrecision/PrecisionWoW#449]
Toggling off a pets ability to be auto used doesnt seem to work, the pet will still cast the ability off cooldown and global cooldown regardless of if its turned on or not.

**Comment by Broker-Precision** [comment]
Unable to reproduce, Was this on a hunter or a warlock?

**Comment by VortexPrecision** [comment]
this is a very rare issue but can happen, I will take a look later on.
