### ISSUE TITLE
Crates in Stratholme

### ISSUE THREAD

**Issue by Peppersprayz** [VortexPrecision/PrecisionWoW#450]
Supply crates in Stratholme are not working properly.

What should happens is that some crates are trapped and drop nothing (it makes spawn some rats instead) and some crates should actually drop some loots, including holly water.

Currently, ALL the crates are trapped and it's impossible t o get the holly water.

You can see in this video how it works when the crate is not trapped : https://youtu.be/zRDE1C3T_Fw?t=45 (at 45 sec).

It's easy to reproduce this bug, go into Stratholme an try to loot all the crates, you will see that they are all trapped.

**Comment by Broker-Precision** [comment]
Fixed
