### ISSUE TITLE
Shaman Weapon Enhancments

### ISSUE THREAD

**Issue by supxdz** [VortexPrecision/PrecisionWoW#458]
If you try to cast a weapon enhancement on a tradable item, the wonder disappears very quickly.

**Comment by Broker-Precision** [comment]
I believe what Sup means is when you use a enchant on the weapon that is a refundable/tradable item (item_template.flags 4096) the confirmation popup disappear before the player accepts or declines.

Seems related to https://github.com/VortexPrecision/PrecisionWoW/issues/443

**Comment by supxdz** [comment]
That is exactly the case
