### ISSUE TITLE
[Quest] [The Battle of Alterac] - 7141

### ISSUE THREAD

**Issue by Broker-Precision** [VortexPrecision/PrecisionWoW#459]
Unable to complete via normal means. Possible issue with NPCs (11946 Drek'Thar) script
Quest is a 2 part, Defeat Drek'Thar & Slay Drek'Thar.

In AV players will only get Defeat Drek'Thar completed.
On testing realm killing Drek'thar outside of AV will complete Slay Drek'thar

**Comment by VortexPrecision** [comment]
quest works for me, not bugged
