### ISSUE TITLE
Mobs fleeing in Eastern Plaguelands

### ISSUE THREAD

**Issue by Bluebies** [VortexPrecision/PrecisionWoW#461]
I have been fighting mobs in EPL w/ my rogue and about 50% of the mobs that I attack starting w/ a stealth attack of some kind (ie Cheap Shot) they will flee for upwards of 15-20 seconds to what seems to be their max distance before evade bugging and then they come back. I have seen a few of them actually run away twice (these are undead mobs, like the banshees).

**Comment by VortexPrecision** [comment]
related: https://github.com/VortexPrecision/PrecisionWoW/issues/456 closing for filtering.
