### ISSUE TITLE
Urok Doomhowl Summon Adds spawning too fast

### ISSUE THREAD

**Issue by supxdz** [VortexPrecision/PrecisionWoW#466]
title

**Comment by Broker-Precision** [comment]
Hello, Would you be able to provide reference to what the correct timer should be? From our documentations and referencing TrinityCore github the timings we have are correct.
Thanks.

**Comment by Broker-Precision** [comment]
Per convo with reporter: Issue is not so much with the timings but the increased healthpools we have customly implemented. With a group of 5 players with half raid gear they were still having issues completing the event.

Possible solutions nerf healthpolls of spawned mobs:
Mages: 10602
Enforcers: 10601

**Comment by Broker-Precision** [comment]
Health Pools of Urok Enforcer, Urok Ogre Magus reduced by 15%
