### ISSUE TITLE
Horde side cant buy Alterac Valley rep items

### ISSUE THREAD

**Issue by Futuron-Sun** [VortexPrecision/PrecisionWoW#490]
Frostwolf's Clan vendors at Orgrimmar, Alterac Valley and Alterac Mountains require Stormspike Guard reputation instead

**Comment by Hobo-Hank** [comment]
the one in org has the correct rep are you sure it wasnt just an xfaction bug?

**Comment by Futuron-Sun** [comment]
thank you. after clearing the cache, reputation became correct
