### ISSUE TITLE
Stratholme Service Entrance (outside the dungeon) not openable

### ISSUE THREAD

**Issue by Peppersprayz** [VortexPrecision/PrecisionWoW#491]
You can't open the door that leads to Stratholme Service Entrance in Eastern Plaguelands.

You should be able to open it with the "Key to the City". 

Edit : the door dosn't work but the lever behind does. Still you can't open from outside

**Comment by VortexPrecision** [comment]
please print screen the entrance point that you mean.

**Comment by Peppersprayz** [comment]
![Door1](https://user-images.githubusercontent.com/78567180/169875014-546ece63-6de1-4b12-9b38-d683992b9047.png)
![Door2](https://user-images.githubusercontent.com/78567180/169875033-73b643e0-c23b-4f6e-9876-32a7c38598a9.png)

**Comment by Broker-Precision** [comment]
Fixed
