### ISSUE TITLE
[QUEST] Kill 'em with sleep deprivation.

### ISSUE THREAD

**Issue by Flodden** [VortexPrecision/PrecisionWoW#495]
Hello its me the annoying hunter Flodden xD
made a new character and found a extremely bugged quest. its better if u go there and find out ureself xD
Kill 'em with sleep deprivation.
Oh and the first problem you will find with it IS NOT THE BIG PROBLEM hahaha
Write to me in ure discord if u need my help

**Comment by Broker-Precision** [comment]
Hi, Whats the issue with this? I've tested it and there was no issue for me.

**Comment by Broker-Precision** [comment]
Working as intended
