### ISSUE TITLE
Lean Wolf Flank recipe

### ISSUE THREAD

**Issue by R3deamer** [VortexPrecision/PrecisionWoW#513]
Super-seller 680 doesn`t spawn in Desolace, neither does Vendor-Tron 1000. they sell the Lean wolf flank recipe needed for the AQ efforts. It has smth to do with the caravan event in desolace.

Wowhead quote from comments: "The Super-Seller 680 and Vendor-Tron 1000 are part of a scripted caravan that travels between two points in Desolace. The 680 appears when the caravan reaches the southern location, and the 1000 appears when it reaches the northern location. The two robots sell different sets of items. When the caravan is at the southern location, one of the two goblins tells you that the 1000 should be set up at the northern location in an hour, but it only seems to take them 15-20 minutes to make the trip and the robot appears immediately. They seem to stay at each location for no more than 10 minutes."

Npc link : https://classic.wowhead.com/npc=12246/super-seller-680

**Comment by Broker-Precision** [comment]
Confirmed both NPCs do spawn when Caravan has reach its north & south destinations.
