### ISSUE TITLE
Quest: testing-for-corruption-felwood / testing-for-impurities-ungoro-crater

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#514]
When you turn in this quest https://classic.wowhead.com/quest=4661/testing-for-corruption-felwood
You should receive https://classic.wowhead.com/item=15103/corrupt-tested-sample

When you turn in this quest https://classic.wowhead.com/quest=4561/testing-for-impurities-ungoro-crater
You should receive https://classic.wowhead.com/item=15102/ungoro-tested-sample

You don't receive either of the samples after turning in

**Comment by Broker-Precision** [comment]
Fixed
