### ISSUE TITLE
[QUEST] ID:11690 [Bring 'Em Back Alive]

### ISSUE THREAD

**Issue by treskoo** [VortexPrecision/PrecisionWoW#534]
Unable to move the kodos when mounting them. They keep laying on the ground.

**Comment by Broker-Precision** [comment]
Hi, Could you please eplain this a bit more. From testing I'm able to move the kodo's

![image](https://github.com/VortexPrecision/PrecisionWoW/assets/77854145/90c5bdbe-489d-46d8-9534-27c67a886683)

**Comment by treskoo** [comment]
This issue seems to be resolved now.
![image](https://github.com/VortexPrecision/PrecisionWoW/assets/64747144/f9e343ee-d101-4171-9b84-54df7719797d)
