### ISSUE TITLE
[QUEST] ID:12583 [Crashed Sprayer]

### ISSUE THREAD

**Issue by treskoo** [VortexPrecision/PrecisionWoW#537]
Unable to interact with the "Crashed Plague Sprayer" object, "Out of range.".
Object ID: 190537
![image](https://github.com/VortexPrecision/PrecisionWoW/assets/64747144/ac33a2b2-05e8-493b-b380-3340e9104439)

**Comment by Broker-Precision** [comment]
Fixed
