### ISSUE TITLE
[QUEST] ID:12326 [Steamtank Surprise]

### ISSUE THREAD

**Issue by treskoo** [VortexPrecision/PrecisionWoW#543]
Whenever you jump out of the tank during the quest Steamtank Surprise in Dragonblight it starts attacking you untill you die. As player you can't attack it back.

![image](https://github.com/VortexPrecision/PrecisionWoW/assets/64747144/b3b981a0-727f-4e71-921e-681b942958aa)

Reported by: Rajaani

**Comment by Broker-Precision** [comment]
Fixed
