### ISSUE TITLE
[RDF] xp

### ISSUE THREAD

**Issue by VortexPrecision** [VortexPrecision/PrecisionWoW#547]
no xp received by completing RDF

**Comment by theblaze001** [comment]
Reported issue is wrong 

Completing XP is granted but is not multiplicative with .xp rate

**Comment by VortexPrecision** [comment]
@theblaze001 someone sent me a print proving that the xp received was only visual, nobody was getting any

**Comment by Broker-Precision** [comment]
Fixed.
