### ISSUE TITLE
[Raid] Naxxramas 10

### ISSUE THREAD

**Issue by treskoo** [VortexPrecision/PrecisionWoW#550]
- Some NPC's in the military quarter is level 60.
- Razuvious's shout goes through walls. Impossible to LoS.
- Level 60 Horsemen chest spawns.

**Comment by VortexPrecision** [comment]
note: in WOTLK you can't LOS razuvious shout.

follow up on https://github.com/VortexPrecision/PrecisionWoW/issues/556
