### ISSUE TITLE
[Raid] Naxxramas 10 man - Wipe = graveyard resurrection

### ISSUE THREAD

**Issue by theblaze001** [VortexPrecision/PrecisionWoW#553]
When you wipe or release in Naxx 10 man you are spawned the the factions graveyard in dragonblight. You do not get Ghost Gryphon why you can not get up again without resurrecting.

To be checked in 25 man

**Comment by VortexPrecision** [comment]
added to https://github.com/VortexPrecision/PrecisionWoW/issues/556
