### ISSUE TITLE
[Raid] Gluth 25 man adds do not scale

### ISSUE THREAD

**Issue by theblaze001** [VortexPrecision/PrecisionWoW#555]
Adds have 500k life after decimate - not possible with less then 25 persons

**Comment by Broker-Precision** [comment]
Issue is with decimation spell, not the scaling of the healthpools.

https://www.wowhead.com/wotlk/spell=28375/decimate
Spell currently only effecting enemy's (players in this case), Should effect all targets (npcs/players)

Quote from wowhead:

"About 2 minutes into the fight, Gluth will use Decimate. This drops the current health of all Zombie Chow and all players in your raid to only 5% of their maximum. Additionally, it causes all Zombie Chow to ignore their current threat and run towards Gluth."

Source: https://www.wowhead.com/wotlk/guide/raids/naxxramas/gluth-strategy

**Comment by VortexPrecision** [comment]
added to https://github.com/VortexPrecision/PrecisionWoW/issues/556
