### ISSUE TITLE
[NPC] List of Northrend Rare's that are immune to magical and physical damage

### ISSUE THREAD

**Issue by mikedej** [VortexPrecision/PrecisionWoW#568]
These are immune to any sort of magical and physical damage. (Except for melee auto-attack and rend)

1. [Tukemuth](https://www.wowhead.com/wotlk/npc=32400/tukemuth) (multiple spawns at 53.60 / 58.47 / 69.58 / 59.39 / 68.31 / 67.38)
2. [Griegen](https://www.wowhead.com/wotlk/npc=32471/griegen) (multiple spawns at 25.76 / 21.77 / 22.70)
3. [Syreian the Bonecarver](https://www.wowhead.com/wotlk/npc=32438/syreian-the-bonecarver)
4. [King Ping](https://www.wowhead.com/wotlk/npc=32398/king-ping)
5. [Vigdis the War Maiden](https://www.wowhead.com/wotlk/npc=32386/vigdis-the-war-maiden) (multiple spawns at 75.60)
6. [Hildana Deathstealer](https://www.wowhead.com/wotlk/npc=32495/hildana-deathstealer)
7. [Fumblub Gearwind](https://www.wowhead.com/wotlk/npc=32358/fumblub-gearwind)
8. [Old Crystalbark](https://www.wowhead.com/wotlk/npc=32357/old-crystalbark) (multiple spawns at 24.35 / 22.29)
9. [Aotona](https://www.wowhead.com/wotlk/npc=32481/aotona) is killable but multiple spawns at 43.52 / 44.52)

**Comment by Broker-Precision** [comment]
Corrected
