### ISSUE TITLE
[DM:North] Gordok Warlock / Doomguard behaviour

### ISSUE THREAD

**Issue by awatenn** [VortexPrecision/PrecisionWoW#8]
You can target Gordok Warlocks or their Doomguard pets and rightclick or type the command "/startattack" from anywhere and it will incorrectly pull them along with all nearby mobs.

https://classic.wowhead.com/npc=11448/gordok-warlock

**Comment by VortexPrecision** [comment]
maybe
https://github.com/TrinityCore/TrinityCore/commit/a891eb364e941a5146fba4af16e1ecf65cdd9239

**Comment by treskoo** [comment]
https://gyazo.com/3351e77e8e75530da50111867b8a807f
